# Generated by Django 4.0.4 on 2023-04-15 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '__first__'),
        ('pais', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas_bancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipocuenta', models.CharField(choices=[('A', 'Ahorro'), ('C', 'Corriente')], help_text='A-ahorro / C-corriente', max_length=1)),
                ('cxcuenta', models.CharField(help_text='Número de cuenta', max_length=15)),
                ('lactiva', models.BooleanField(default=True)),
                ('cxbanco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cuenta', to='pais.bancos')),
                ('cxcliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.datos_generales')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndevolucion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dmovimiento', models.DateField()),
                ('cxtransferencia', models.CharField(max_length=10)),
                ('cuentadestino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_destino', to='empresa.cuentas_bancarias')),
                ('cuentaorigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentasconjuntas.cuentas_bancarias')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('dmovimiento', models.DateField()),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxtipo', models.CharField(choices=[('R', 'Recuperación'), ('D', 'Débito'), ('P', 'Protesto'), ('T', 'Transferencia'), ('C', 'Cobranza')], max_length=2)),
                ('cxmovimiento', models.CharField(max_length=10)),
                ('cuentabancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentasconjuntas.cuentas_bancarias')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
