# Generated by Django 4.0.4 on 2023-08-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasconjuntas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencias',
            name='cxtransferencia',
        ),
    ]
