# Generated by Django 4.0.4 on 2023-08-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0042_cuentas_cargosfactoring'),
        ('cuentasconjuntas', '0002_remove_transferencias_cxtransferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias',
            name='cxasiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_transferencia', to='contabilidad.diario_cabecera'),
        ),
        migrations.AddField(
            model_name='transferencias',
            name='lcontabilizado',
            field=models.BooleanField(default=False),
        ),
    ]
