# Generated by Django 4.0.4 on 2023-01-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasconjuntas', '0002_remove_movimientos_cxmovimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='dmovimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transferencias',
            name='dmovimiento',
            field=models.DateField(null=True),
        ),
    ]
