# Generated by Django 4.0.4 on 2023-01-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasconjuntas', '0004_alter_transferencias_dmovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='dmovimiento',
            field=models.DateField(),
        ),
    ]
