# Generated by Django 4.0.4 on 2022-09-29 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('operaciones', '0034_alter_asignacion_cxestado_and_more'),
        ('pais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcobranza', models.DateTimeField(auto_created=True)),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcobraza', models.CharField(max_length=8)),
                ('cxformapago', models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('TRA', 'Transferencia'), ('MOV', 'Movimiento contable')], max_length=3)),
                ('cxlocalidad', models.CharField(blank=True, max_length=4)),
                ('dliquidacion', models.DateTimeField()),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsobrepago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxestado', models.CharField(default=' ', max_length=1)),
                ('ctcuentatransferencia', models.CharField(max_length=15, null=True)),
                ('cxcuentadeposito', models.CharField(max_length=15, null=True)),
                ('cxbancodeposito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_deposito', to='pais.bancos')),
                ('cxbancotransferencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_transferencia', to='pais.bancos')),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cobranza', to='empresa.datos_participantes', to_field='cxparticipante')),
                ('cxtipofactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_cobranza', to='empresa.tipos_factoring', to_field='cxtipofactoring')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalorcobranza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nvalorbaja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nretenciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsaldoaldia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndiasacondonar', models.SmallIntegerField(default=0)),
                ('cxusuariocondona', models.IntegerField(null=True)),
                ('cxcobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.documentos_cabecera')),
                ('cxdocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.documentos')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcheque', models.CharField(max_length=8)),
                ('cxtipoparticipante', models.CharField(choices=[('M', 'Comprador'), ('C', 'Cliente')], max_length=1)),
                ('ctcuenta', models.CharField(max_length=15)),
                ('ctcheque', models.CharField(max_length=8)),
                ('ctgirador', models.CharField(max_length=60)),
                ('cxestado', models.CharField(default=' ', max_length=1)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demision', models.DateTimeField()),
                ('cxbanco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cheque', to='pais.bancos')),
                ('cxparticipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cheque', to='empresa.datos_participantes', to_field='cxparticipante')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
