# Generated by Django 4.0.4 on 2023-06-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='lfacturagenerada',
            field=models.BooleanField(default=False),
        ),
    ]
