# Generated by Django 4.0.4 on 2022-10-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0002_remove_documentos_cabecera_cxbancodeposito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_cabecera',
            name='ddeposito',
            field=models.DateTimeField(null=True),
        ),
    ]
