# Generated by Django 4.0.4 on 2023-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0002_liquidacion_cabecera_lfacturagenerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='nporcentajeiva',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
