# Generated by Django 4.0.4 on 2022-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0003_documentos_cabecera_ddeposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_cabecera',
            name='ldepositoencuentaconjunta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentos_cabecera',
            name='lpagadoporelcliente',
            field=models.BooleanField(default=False),
        ),
    ]
