# Generated by Django 4.0.4 on 2022-10-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0041_alter_cuentas_bancarias_cxparticipante'),
        ('cobranzas', '0005_remove_cheques_cxcheque_remove_cheques_demision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos_cabecera',
            name='ctcuentatransferencia',
        ),
        migrations.RemoveField(
            model_name='documentos_cabecera',
            name='cxbancotransferencia',
        ),
        migrations.AddField(
            model_name='documentos_cabecera',
            name='cxcuentatransferencia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuentas_bancarias'),
            preserve_default=False,
        ),
    ]
