# Generated by Django 4.0.4 on 2023-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0006_documentos_cabecera_asiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion_detalle',
            name='cxtipooperacion',
            field=models.CharField(choices=[('R', 'Recuperación'), ('C', 'Cobranzas'), ('L', 'Liquidación'), ('D', 'Debito bancario'), ('F', 'Factura')], max_length=1),
        ),
    ]
