# Generated by Django 4.0.4 on 2022-10-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0042_alter_cuentas_bancarias_cxbanco'),
        ('cobranzas', '0006_remove_documentos_cabecera_ctcuentatransferencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheques',
            name='ctcuenta',
        ),
        migrations.RemoveField(
            model_name='cheques',
            name='cxbanco',
        ),
        migrations.AddField(
            model_name='cheques',
            name='cxcuentabancaria',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuentas_bancarias'),
            preserve_default=False,
        ),
    ]
