# Generated by Django 4.0.4 on 2022-10-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_alter_cuentas_bancarias_cxbanco'),
        ('cobranzas', '0007_remove_cheques_ctcuenta_remove_cheques_cxbanco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques',
            name='cxcuentabancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuentas_bancarias'),
        ),
    ]
