# Generated by Django 4.0.4 on 2023-08-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0040_alter_cuentas_especiales_liquidacionennegativo'),
        ('cobranzas', '0007_alter_liquidacion_detalle_cxtipooperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques_protestados',
            name='asiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_protesto', to='contabilidad.diario_cabecera'),
        ),
        migrations.AddField(
            model_name='cheques_protestados',
            name='lcontabilizada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cheques_protestados',
            name='cxtipooperacion',
            field=models.CharField(choices=[('C', 'Cobranza'), ('R', 'Recuperacion')], max_length=1),
        ),
    ]
