# Generated by Django 4.0.4 on 2022-10-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0008_alter_cheques_cxcuentabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='dliquidacion',
            field=models.DateTimeField(null=True),
        ),
    ]
