# Generated by Django 4.0.4 on 2022-10-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0009_alter_documentos_cabecera_dliquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxcheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cobranzas.cheques'),
        ),
    ]
