# Generated by Django 4.0.4 on 2024-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0009_recuperaciones_cabecera_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='jotroscargos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='nbaseiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='nbasenoiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='notroscargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
