# Generated by Django 4.0.4 on 2022-10-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_alter_cuentas_bancarias_cxbanco'),
        ('cobranzas', '0010_alter_documentos_cabecera_cxcheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxcuentatransferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuentas_bancarias'),
        ),
    ]
