# Generated by Django 4.0.4 on 2024-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0012_pagare_detalle_cuota_pagare_detalle_cxusuariocrea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagare_cabecera',
            name='nsobrepago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
