# Generated by Django 4.0.4 on 2022-10-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0012_alter_documentos_cabecera_cxcuentadeposito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos_cabecera',
            old_name='cxcobraza',
            new_name='cxcobranza',
        ),
    ]
