# Generated by Django 4.0.4 on 2024-08-05 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0011_alter_empresas_ctnombre'),
        ('operaciones', '0035_pagare_detalle_cxestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranzas', '0013_pagare_cabecera_nsobrepago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('lfacturagenerada', models.BooleanField(default=False)),
                ('cobranzacuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.pagare_detalle')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.pagare_detalle')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
