# Generated by Django 4.0.4 on 2022-10-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0035_alter_chequesaccesorios_documento'),
        ('cobranzas', '0013_rename_cxcobraza_documentos_cabecera_cxcobranza'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_cabecera',
            name='cxaccesorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='operaciones.chequesaccesorios'),
        ),
    ]
