# Generated by Django 4.0.4 on 2022-11-05 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranzas', '0014_documentos_cabecera_cxaccesorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxformapago',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('MOV', 'Movimiento contable'), ('TRA', 'Transferencia'), ('DEP', 'Deposito de accesorio')], max_length=3),
        ),
        migrations.AlterField(
            model_name='documentos_detalle',
            name='cxusuariocondona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocondona', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
