# Generated by Django 4.0.4 on 2022-11-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranzas', '0015_alter_documentos_cabecera_cxformapago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_detalle',
            name='cxusuariocondona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocondona', to=settings.AUTH_USER_MODEL),
        ),
    ]
