# Generated by Django 4.0.4 on 2024-08-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0015_factura_cuota_nbaseiva_factura_cuota_nbasenoiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagare_detalle',
            name='nvaloraplicainteres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
