# Generated by Django 5.1.5 on 2025-04-12 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0017_alter_empresas_ilogocorto_alter_empresas_ilogolargo'),
        ('cobranzas', '0016_pagare_detalle_nvaloraplicainteres'),
        ('contabilidad', '0045_alter_factura_venta_cxtipooperacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheques_protestados_historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxformacobro', models.CharField(choices=[('CHE', 'Cheque'), ('DEP', 'Deposito de accesorio')], max_length=3)),
                ('dprotesto', models.DateField()),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nvalorcartera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsaldocartera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cxestado', models.CharField(default='A', max_length=1)),
                ('dultimacobranza', models.DateTimeField(null=True)),
                ('cxtipooperacion', models.CharField(choices=[('C', 'Cobranza'), ('R', 'Recuperacion')], max_length=1)),
                ('lcontabilizada', models.BooleanField(default=False)),
                ('asiento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_protesto_historico', to='contabilidad.diario_cabecera')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_protestado_historico', to='cobranzas.cheques')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
