# Generated by Django 4.0.4 on 2022-11-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_alter_cuentas_bancarias_cxbanco'),
        ('cobranzas', '0016_alter_documentos_detalle_cxusuariocondona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cobranza', to='clientes.datos_generales', to_field='cxcliente'),
        ),
    ]
