# Generated by Django 5.1.5 on 2025-04-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0017_cheques_protestados_historico'),
        ('operaciones', '0044_cheques_quitados_historico_cortes_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques_protestados_historico',
            name='historico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_protestado_historico', to='operaciones.cortes_historico'),
        ),
        migrations.AddField(
            model_name='cheques_protestados_historico',
            name='motivoprotesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.motivos_protesto_maestro'),
        ),
        migrations.AddField(
            model_name='cheques_protestados_historico',
            name='notadedebito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.notas_debito_cabecera'),
        ),
    ]
