# Generated by Django 4.0.4 on 2022-11-08 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0043_alter_cuentas_bancarias_cxbanco'),
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('operaciones', '0035_alter_chequesaccesorios_documento'),
        ('cobranzas', '0017_alter_documentos_cabecera_cxcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion_cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxliquidacion', models.CharField(max_length=8, unique=True)),
                ('jcobranzas', models.JSONField()),
                ('nvuelto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsobrepago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ngao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ngaoa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndescuentodecartera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nretenciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nbajas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('niva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nneto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctinstrucciondepago', models.TextField(blank=True)),
                ('dliquidacion', models.DateTimeField(null=True)),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_liquidacion', to='clientes.datos_generales', to_field='cxcliente')),
                ('cxtipofactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_liquidacioncobranzas', to='empresa.tipos_factoring', to_field='cxtipofactoring')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liquidacion_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nbase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndias', models.SmallIntegerField(default=0)),
                ('ntasa', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cxcobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.documentos_cabecera')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.documentos')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_detalle', to='cobranzas.liquidacion_cabecera')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.movimientos_maestro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
