# Generated by Django 4.0.4 on 2022-11-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('cobranzas', '0018_liquidacion_cabecera_liquidacion_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion_cabecera',
            name='dliquidacion',
        ),
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='cxcuentapago',
            field=models.ForeignKey(default=20220101, on_delete=django.db.models.deletion.RESTRICT, to='empresa.cuentas_bancarias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='ddesembolso',
            field=models.DateTimeField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liquidacion_cabecera',
            name='ctinstrucciondepago',
            field=models.TextField(),
        ),
    ]
