# Generated by Django 5.1.5 on 2025-04-13 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0017_alter_empresas_ilogocorto_alter_empresas_ilogolargo'),
        ('cobranzas', '0018_cheques_protestados_historico_historico_and_more'),
        ('operaciones', '0044_cheques_quitados_historico_cortes_historico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_protestados_historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nsaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nvalorbajacobranza', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsaldobajacobranza', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxestado', models.CharField(default='A', max_length=1)),
                ('dultimacobranza', models.DateTimeField(null=True)),
                ('accesorio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.chequesaccesorios')),
                ('chequeprotestado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cobranzas.cheques_protestados_historico')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.documentos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documento_protestado_historico', to='operaciones.cortes_historico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
