# Generated by Django 4.0.4 on 2022-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0019_remove_liquidacion_cabecera_dliquidacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='dliquidacion',
            field=models.DateTimeField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
