# Generated by Django 5.1.5 on 2025-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0019_documentos_protestados_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques_protestados_historico',
            name='idanterior',
            field=models.BigIntegerField(default=0),
        ),
    ]
