# Generated by Django 4.0.4 on 2022-11-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0036_remove_cargos_detalle_cxcobranza_and_more'),
        ('cobranzas', '0020_liquidacion_cabecera_dliquidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion_detalle',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='liquidacion_detalle',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='liquidacion_detalle',
            name='nbase',
        ),
        migrations.RemoveField(
            model_name='liquidacion_detalle',
            name='ndias',
        ),
        migrations.RemoveField(
            model_name='liquidacion_detalle',
            name='ntasa',
        ),
        migrations.AddField(
            model_name='liquidacion_detalle',
            name='cargo',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.RESTRICT, to='operaciones.cargos_detalle'),
            preserve_default=False,
        ),
    ]
