# Generated by Django 5.1.5 on 2025-06-22 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configuracion_twilio_whatsapp'),
        ('bases', '0022_alter_version_detalle_ctenlace_and_more'),
        ('cobranzas', '0020_cheques_protestados_historico_idanterior'),
        ('operaciones', '0046_revision_cartera_cxtipoparticipante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion_cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipoparticipante', models.CharField(choices=[('C', 'Cliente'), ('D', 'Deudor')], max_length=1)),
                ('cxestado', models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada'), ('P', 'Pendiente'), ('R', 'Reprogramada')], default='P', max_length=1)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('revision_cartera_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_cartera_cliente', to='operaciones.revision_cartera_detalle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Twilio_whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('ctfrom', models.CharField(max_length=25, verbose_name='De')),
                ('ctto', models.CharField(max_length=25, verbose_name='Para')),
                ('ctbody', models.TextField(verbose_name='Mensaje')),
                ('ctsid', models.CharField(max_length=100, unique=True, verbose_name='SID')),
                ('ctstatus', models.CharField(max_length=20, verbose_name='Estado')),
                ('ctdirection', models.CharField(max_length=30, verbose_name='Dirección')),
                ('jcontexto', models.JSONField(verbose_name='Contexto')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.configuracion_twilio_whatsapp')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('gestion_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestion_cobro_whatsapp', to='cobranzas.gestion_cobro')),
            ],
            options={
                'verbose_name': 'Mensaje de WhatsApp',
                'verbose_name_plural': 'Mensajes de WhatsApp',
            },
        ),
    ]
