# Generated by Django 5.1.5 on 2025-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0021_gestion_cobro_twilio_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion_cobro',
            name='ctnumerowhatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
