# Generated by Django 4.0.4 on 2022-11-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0021_remove_liquidacion_detalle_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion_cabecera',
            name='cxcuentapago',
        ),
    ]
