# Generated by Django 4.0.4 on 2022-11-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0022_remove_liquidacion_cabecera_cxcuentapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='ldesembolsada',
            field=models.BooleanField(default=False),
        ),
    ]
