# Generated by Django 5.1.5 on 2026-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0022_gestion_cobro_ctnumerowhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_cabecera',
            name='ctcomentarios',
            field=models.TextField(blank=True),
        ),
    ]
