# Generated by Django 5.1.5 on 2026-01-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0023_documentos_cabecera_ctcomentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos_cabecera',
            old_name='ctcomentarios',
            new_name='ctcomentario',
        ),
    ]
