# Generated by Django 4.0.4 on 2022-11-20 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0046_delete_cheques_protestados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranzas', '0023_liquidacion_cabecera_ldesembolsada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheques_protestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('dprotesto', models.DateField()),
                ('nvalornotadebito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nsaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cxestado', models.CharField(default='A', max_length=1)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cobranzas.cheques')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('motivoprotesto', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.motivos_protesto_maestro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
