# Generated by Django 4.0.4 on 2022-11-21 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranzas', '0024_cheques_protestados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques_protestados',
            name='cxformacobro',
            field=models.CharField(choices=[('CHE', 'Cheque'), ('DEP', 'Deposito de accesorio')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Documentos_protestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('documento', models.BigIntegerField()),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nsaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cxestado', models.CharField(default='A', max_length=1)),
                ('chequeprotestado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cobranzas.cheques_protestados')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
