# Generated by Django 5.1.5 on 2026-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0024_rename_ctcomentarios_documentos_cabecera_ctcomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='ctcomentario',
            field=models.TextField(blank=True, default=''),
        ),
    ]
