# Generated by Django 5.1.5 on 2026-01-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0025_alter_documentos_cabecera_ctcomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperaciones_cabecera',
            name='ctcomentario',
            field=models.TextField(blank=True, default=''),
        ),
    ]
