# Generated by Django 4.0.4 on 2022-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0025_cheques_protestados_cxformacobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_protestados',
            name='nsaldobaja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentos_protestados',
            name='nvalorbaja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
