# Generated by Django 5.1.5 on 2026-02-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0026_recuperaciones_cabecera_ctcomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='lgenerand',
            field=models.BooleanField(default=False),
        ),
    ]
