# Generated by Django 4.0.4 on 2022-11-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0047_alter_notas_debito_cabecera_cxcliente'),
        ('cobranzas', '0026_documentos_protestados_nsaldobaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques_protestados',
            name='motivoprotesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.motivos_protesto_maestro'),
        ),
    ]
