# Generated by Django 5.1.5 on 2026-02-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0027_liquidacion_cabecera_lgenerand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidacion_cabecera',
            old_name='lgenerand',
            new_name='lincluyecargosprevios',
        ),
    ]
