# Generated by Django 4.0.4 on 2022-11-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0047_alter_notas_debito_cabecera_cxcliente'),
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('clientes', '0044_remove_datos_generales_ctbeneficiarioliquidacionasignacion_and_more'),
        ('cobranzas', '0027_alter_cheques_protestados_motivoprotesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuperaciones_cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcobranza', models.DateTimeField(auto_created=True)),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxrecuperacion', models.CharField(max_length=8)),
                ('cxtipoparticipante', models.CharField(choices=[('D', 'Deudor'), ('C', 'Cliente')], max_length=1)),
                ('cxformacobro', models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('MOV', 'Movimiento contable'), ('TRA', 'Transferencia')], max_length=3)),
                ('cxlocalidad', models.CharField(blank=True, max_length=4)),
                ('dliquidacion', models.DateTimeField(null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsobrepago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxestado', models.CharField(default=' ', max_length=1)),
                ('ddeposito', models.DateTimeField(null=True)),
                ('chequeprotestado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cobranzas.cheques_protestados')),
                ('cxcheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cobranzas.cheques')),
                ('cxcuentadeposito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='empresa.cuentas_bancarias')),
                ('cxcuentatransferencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuentas_bancarias')),
                ('cxparticipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante')),
                ('cxtipofactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.tipos_factoring', to_field='cxtipofactoring')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='documentos_protestados',
            name='accesorio',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='documentos_protestados',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.documentos'),
        ),
        migrations.CreateModel(
            name='Recuperaciones_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalorrecuperacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nvalorbaja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsaldoaldia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndiasacondonar', models.SmallIntegerField(default=0, null=True)),
                ('cxdocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.documentos')),
                ('cxusuariocondona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('recuperacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.recuperaciones_cabecera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
