# Generated by Django 5.1.5 on 2026-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0028_rename_lgenerand_liquidacion_cabecera_lincluyecargosprevios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxestado',
            field=models.CharField(choices=[('A', ''), ('C', 'Confirmada'), ('P', 'Protestada'), ('L', 'Liquidada'), ('E', 'Eliminada')], default='A', max_length=1),
        ),
    ]
