# Generated by Django 4.0.4 on 2022-11-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0047_alter_notas_debito_cabecera_cxcliente'),
        ('cobranzas', '0028_recuperaciones_cabecera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_protestados',
            name='accesorio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.chequesaccesorios'),
        ),
    ]
