# Generated by Django 5.1.5 on 2026-08-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0029_alter_documentos_cabecera_cxestado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twilio_whatsapp',
            options={},
        ),
        migrations.AlterField(
            model_name='gestion_cobro',
            name='ctnumerowhatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
