# Generated by Django 4.0.4 on 2022-11-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0030_rename_nsaldobaja_documentos_protestados_nsaldobajacobranza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_protestados',
            name='dultimacobranza',
            field=models.DateTimeField(null=True),
        ),
    ]
