# Generated by Django 4.0.4 on 2022-11-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0031_documentos_protestados_dultimacobranza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuperaciones_detalle',
            name='cxdocumento',
        ),
        migrations.AddField(
            model_name='recuperaciones_detalle',
            name='documentoprotestado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cobranzas.documentos_protestados'),
            preserve_default=False,
        ),
    ]
