# Generated by Django 4.0.4 on 2022-11-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0032_remove_recuperaciones_detalle_cxdocumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques_protestados',
            name='dultimacobranza',
            field=models.DateTimeField(null=True),
        ),
    ]
