# Generated by Django 4.0.4 on 2022-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0033_cheques_protestados_dultimacobranza'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperaciones_detalle',
            name='nsaldoaldiabajacobranza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
