# Generated by Django 4.0.4 on 2022-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0035_cheques_protestados_cxtipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques_protestados',
            name='cxtipooperacion',
            field=models.CharField(max_length=1, default='C'),
        ),
    ]
