# Generated by Django 4.0.4 on 2022-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0036_alter_cheques_protestados_cxtipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques_protestados',
            name='cxtipooperacion',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
