# Generated by Django 4.0.4 on 2022-11-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0044_remove_datos_generales_ctbeneficiarioliquidacionasignacion_and_more'),
        ('cobranzas', '0037_alter_cheques_protestados_cxtipooperacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuperaciones_cabecera',
            name='cxparticipante',
        ),
        migrations.AddField(
            model_name='recuperaciones_cabecera',
            name='cxcliente',
            field=models.ForeignKey(default='0993220167001', on_delete=django.db.models.deletion.CASCADE, to='clientes.datos_generales', to_field='cxcliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheques_protestados',
            name='cxtipooperacion',
            field=models.CharField(max_length=1),
        ),
    ]
