# Generated by Django 4.0.4 on 2022-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0038_remove_recuperaciones_cabecera_cxparticipante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion_detalle',
            name='cxcobranza',
        ),
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='cxtipooperacion',
            field=models.CharField(choices=[('R', 'Recuperación'), ('C', 'Cobranzas')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion_detalle',
            name='operacion',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
