# Generated by Django 4.0.4 on 2022-12-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0039_remove_liquidacion_detalle_cxcobranza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuperaciones_cabecera',
            name='cxtipoparticipante',
        ),
    ]
