# Generated by Django 4.0.4 on 2022-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0040_remove_recuperaciones_cabecera_cxtipoparticipante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion_detalle',
            name='operacion',
        ),
        migrations.AddField(
            model_name='liquidacion_detalle',
            name='cxoperacion',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
