# Generated by Django 4.0.4 on 2022-12-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0041_remove_liquidacion_detalle_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxcheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_cobranza', to='cobranzas.cheques'),
        ),
        migrations.AlterField(
            model_name='recuperaciones_cabecera',
            name='cxcheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_recuperacion', to='cobranzas.cheques'),
        ),
    ]
