# Generated by Django 4.0.4 on 2022-12-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0042_alter_documentos_cabecera_cxcheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques_protestados',
            name='cheque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_protestado', to='cobranzas.cheques'),
        ),
    ]
