# Generated by Django 4.0.4 on 2022-12-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0043_alter_cheques_protestados_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_detalle',
            name='nvaloraplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
