# Generated by Django 4.0.4 on 2022-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0045_alter_liquidacion_detalle_nvaloraplicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion_cabecera',
            name='cxtipooperacion',
        ),
        migrations.AddField(
            model_name='liquidacion_detalle',
            name='cxtipooperacion',
            field=models.CharField(choices=[('R', 'Recuperación'), ('C', 'Cobranzas')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion_detalle',
            name='operacion',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
