# Generated by Django 4.0.4 on 2022-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0047_remove_liquidacion_detalle_cxoperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='cxtipooperacion',
            field=models.CharField(choices=[('R', 'Recuperación'), ('C', 'Cobranzas')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liquidacion_detalle',
            name='cxtipooperacion',
            field=models.CharField(choices=[('R', 'Recuperación'), ('C', 'Cobranzas'), ('L', 'Liquidación')], max_length=1),
        ),
    ]
