# Generated by Django 4.0.4 on 2022-12-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0048_alter_notas_debito_cabecera_cxtipooperacion'),
        ('cobranzas', '0048_liquidacion_cabecera_cxtipooperacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion_detalle',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.cargos_detalle'),
        ),
    ]
