# Generated by Django 4.0.4 on 2023-01-16 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('operaciones', '0049_remove_notas_debito_cabecera_cheque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0044_remove_datos_generales_ctbeneficiarioliquidacionasignacion_and_more'),
        ('cobranzas', '0049_alter_liquidacion_detalle_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos_cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcobranza', models.DateTimeField(auto_created=True)),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcobranza', models.CharField(max_length=8)),
                ('cxformapago', models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('MOV', 'Movimiento contable'), ('TRA', 'Transferencia'), ('DEP', 'Deposito de accesorio')], max_length=3)),
                ('cxlocalidad', models.CharField(blank=True, max_length=4)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxestado', models.CharField(default=' ', max_length=1)),
                ('ddeposito', models.DateTimeField(null=True)),
                ('cxcheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_cobranza_cargos', to='cobranzas.cheques')),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cobranza_cargos', to='clientes.datos_generales', to_field='cxcliente')),
                ('cxcuentadeposito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='banco_deposito_cargos', to='empresa.cuentas_bancarias')),
                ('cxcuentatransferencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuentas_bancarias')),
                ('cxtipofactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_cobranza_cargos', to='empresa.tipos_factoring', to_field='cxtipofactoring')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargos_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nsaldoaldia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nvalorcobranza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jcargos', models.JSONField()),
                ('cxcobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.cargos_cabecera')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('notadedebito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.notas_debito_cabecera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
