# Generated by Django 4.0.4 on 2023-01-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasconjuntas', '0001_initial'),
        ('cobranzas', '0051_cargos_cabecera_nsobrepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_cabecera',
            name='cxcuentaconjunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_deposito', to='cuentasconjuntas.cuentas_bancarias'),
        ),
    ]
