# Generated by Django 4.0.4 on 2023-01-24 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0050_alter_notas_debito_cabecera_cxtipooperacion'),
        ('cobranzas', '0052_documentos_cabecera_cxcuentaconjunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitosCuentasConjuntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctmotivo', models.CharField(max_length=60)),
                ('cobranza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.documentos_cabecera')),
                ('cuentabancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cuentas_bancarias')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('notadedebito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operaciones.notas_debito_cabecera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
