# Generated by Django 4.0.4 on 2023-01-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0053_debitoscuentasconjuntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitoscuentasconjuntas',
            name='dmovimiento',
            field=models.DateField(null=True),
        ),
    ]
