# Generated by Django 4.0.4 on 2023-01-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0054_debitoscuentasconjuntas_dmovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitoscuentasconjuntas',
            name='dmovimiento',
            field=models.DateField(),
        ),
    ]
