# Generated by Django 4.0.4 on 2023-01-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasconjuntas', '0006_rename_movimiento_movimientos_cxmovimiento_and_more'),
        ('cobranzas', '0055_alter_debitoscuentasconjuntas_dmovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitoscuentasconjuntas',
            name='cuentabancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentasconjuntas.cuentas_bancarias'),
        ),
    ]
