# Generated by Django 4.0.4 on 2023-01-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0056_alter_debitoscuentasconjuntas_cuentabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitoscuentasconjuntas',
            name='cobranza',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranzas.documentos_cabecera'),
        ),
    ]
