# Generated by Django 4.0.4 on 2023-01-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('cobranzas', '0057_alter_debitoscuentasconjuntas_cobranza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_cobranza_cargos', to='empresa.tipos_factoring', to_field='cxtipofactoring'),
        ),
    ]
