# Generated by Django 4.0.4 on 2023-01-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasconjuntas', '0006_rename_movimiento_movimientos_cxmovimiento_and_more'),
        ('cobranzas', '0058_alter_cargos_cabecera_cxtipofactoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperaciones_cabecera',
            name='cxcuentaconjunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuentaconjunta_deposito', to='cuentasconjuntas.cuentas_bancarias'),
        ),
        migrations.AddField(
            model_name='recuperaciones_cabecera',
            name='ldepositoencuentaconjunta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recuperaciones_cabecera',
            name='lpagadoporelcliente',
            field=models.BooleanField(default=False),
        ),
    ]
