# Generated by Django 4.0.4 on 2023-02-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0059_recuperaciones_cabecera_cxcuentaconjunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitoscuentasconjuntas',
            name='cobranza',
        ),
        migrations.AddField(
            model_name='debitoscuentasconjuntas',
            name='cxtipooperacion',
            field=models.CharField(choices=[('R', 'Recuperación'), ('C', 'Cobranzas')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='debitoscuentasconjuntas',
            name='operacion',
            field=models.BigIntegerField(null=True),
        ),
    ]
