# Generated by Django 4.0.4 on 2023-02-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0060_remove_debitoscuentasconjuntas_cobranza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion_detalle',
            name='cxtipooperacion',
            field=models.CharField(choices=[('R', 'Recuperación'), ('C', 'Cobranzas'), ('L', 'Liquidación'), ('D', 'Debito bancario')], max_length=1),
        ),
    ]
