# Generated by Django 4.0.4 on 2023-02-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0061_alter_liquidacion_detalle_cxtipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxestado',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='recuperaciones_cabecera',
            name='cxestado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
