# Generated by Django 4.0.4 on 2023-02-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0057_datos_operativos_cxestado'),
        ('cobranzas', '0062_alter_documentos_cabecera_cxestado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheques_protestados',
            name='nvalornotadebito',
        ),
        migrations.AddField(
            model_name='cheques_protestados',
            name='notadedebito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.notas_debito_cabecera'),
        ),
    ]
