# Generated by Django 4.0.4 on 2023-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0063_remove_cheques_protestados_nvalornotadebito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='cxestado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
