# Generated by Django 4.0.4 on 2023-02-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0064_liquidacion_cabecera_cxestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques_protestados',
            name='naplicadoacartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
