# Generated by Django 4.0.4 on 2023-02-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0065_cheques_protestados_naplicadoacartera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheques_protestados',
            old_name='nsaldo',
            new_name='nsaldocartera',
        ),
        migrations.RenameField(
            model_name='cheques_protestados',
            old_name='naplicadoacartera',
            new_name='nvalorcartera',
        ),
    ]
