# Generated by Django 4.0.4 on 2023-03-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0066_rename_nsaldo_cheques_protestados_nsaldocartera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='dcobranza',
            field=models.DateField(auto_created=True),
        ),
    ]
