# Generated by Django 4.0.4 on 2023-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0068_documentos_detalle_accesorioquitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperaciones_cabecera',
            name='dcobranza',
            field=models.DateField(auto_created=True),
        ),
    ]
