# Generated by Django 4.0.4 on 2023-03-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0071_remove_ampliaciones_plazo_cabecera_cxampliacion_and_more'),
        ('cobranzas', '0069_alter_recuperaciones_cabecera_dcobranza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitoscuentasconjuntas',
            name='notadedebito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debito_cuenta', to='operaciones.notas_debito_cabecera'),
        ),
    ]
