# Generated by Django 4.0.4 on 2023-03-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0072_chequesaccesorios_ncontadorprorrogas_and_more'),
        ('cobranzas', '0070_alter_debitoscuentasconjuntas_notadedebito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitoscuentasconjuntas',
            name='notadedebito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debito_cuentaconjunta', to='operaciones.notas_debito_cabecera'),
        ),
    ]
