# Generated by Django 4.0.4 on 2023-04-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0071_alter_debitoscuentasconjuntas_notadedebito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion_cabecera',
            name='cxliquidacion',
            field=models.CharField(max_length=8),
        ),
    ]
