# Generated by Django 4.0.4 on 2023-04-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_alter_funcionarios_cxfuncionario_and_more'),
        ('cobranzas', '0072_alter_liquidacion_cabecera_cxliquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_cobranza_cargos', to='empresa.tipos_factoring'),
        ),
        migrations.AlterField(
            model_name='documentos_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_cobranza', to='empresa.tipos_factoring'),
        ),
        migrations.AlterField(
            model_name='liquidacion_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_liquidacioncobranzas', to='empresa.tipos_factoring'),
        ),
        migrations.AlterField(
            model_name='recuperaciones_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.tipos_factoring'),
        ),
    ]
