# Generated by Django 4.0.4 on 2023-04-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('cobranzas', '0073_alter_cargos_cabecera_cxtipofactoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos_cabecera',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargos_detalle',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheques',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheques_protestados',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitoscuentasconjuntas',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentos_cabecera',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentos_detalle',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentos_protestados',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion_cabecera',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion_detalle',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuperaciones_cabecera',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuperaciones_detalle',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
    ]
