# Generated by Django 4.0.4 on 2023-08-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='ctbanco',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feriados',
            name='dferiado',
            field=models.DateField(),
        ),
    ]
