# Generated by Django 5.1.5 on 2026-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0020_datos_participantes_canton_and_more'),
        ('pais', '0004_remove_actividades_cxusuariocrea_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividades',
        ),
    ]
