# Generated by Django 5.1.5 on 2026-03-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0005_delete_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantones',
            name='cxcantones',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='provincias',
            name='cxprovincia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cantones',
            name='ctcantones',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='ctprovincia',
            field=models.CharField(max_length=50),
        ),
    ]
