# Generated by Django 5.1.5 on 2026-03-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0006_cantones_cxcantones_provincias_cxprovincia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cantones',
            old_name='ctcantones',
            new_name='ctcanton',
        ),
        migrations.RenameField(
            model_name='cantones',
            old_name='cxcantones',
            new_name='cxcanton',
        ),
    ]
