# Generated by Django 5.1.5 on 2026-09-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0007_rename_ctcantones_cantones_ctcanton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancos',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='cantones',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='feriados',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='provincias',
            name='empresa',
        ),
    ]
