# Generated by Django 5.1.5 on 2025-02-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_slack',
            name='ctappid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
