# Generated by Django 4.0.4 on 2023-04-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctnombre', models.CharField(max_length=60)),
                ('lgratis', models.BooleanField(default=True)),
                ('nmaximooperaciones', models.SmallIntegerField(default=10)),
                ('lbloqueada', models.BooleanField(default=False)),
                ('dcreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
