# Generated by Django 4.0.4 on 2023-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='ctcontribuyenteespecial',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='empresas',
            name='ctdireccion',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='empresas',
            name='ctgerente',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='empresas',
            name='ctruccompania',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='empresas',
            name='lregimenrimpe',
            field=models.BooleanField(default=False),
        ),
    ]
