# Generated by Django 4.0.4 on 2023-05-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_empresas_ctcontribuyenteespecial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='cxusuariomodifica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='dmodificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
