# Generated by Django 4.0.4 on 2023-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_empresas_cxusuariomodifica_empresas_dmodificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='ambientesri',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
