# Generated by Django 4.0.4 on 2023-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_empresas_ambientesri'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='ctciudad',
            field=models.CharField(default='', max_length=20),
        ),
    ]
