# Generated by Django 4.0.4 on 2023-08-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0007_empresas_dfinpruebas_empresas_diniciooperaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='ltasasfactoringconfiguradas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresas',
            name='ltipofactoringconfigurado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ctnombre',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
