# Generated by Django 4.0.4 on 2023-08-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0008_empresas_ltasasfactoringconfiguradas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ctdireccion',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ctgerente',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ctruccompania',
            field=models.CharField(default='', max_length=13, null=True),
        ),
    ]
