# Generated by Django 4.0.4 on 2023-08-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0009_alter_empresas_ctdireccion_alter_empresas_ctgerente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ambientesri',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1),
        ),
    ]
