# Generated by Django 4.0.4 on 2023-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0010_alter_empresas_ambientesri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ctnombre',
            field=models.CharField(blank=True, default='', max_length=60),
            preserve_default=False,
        ),
    ]
