# Generated by Django 4.2.5 on 2024-12-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0012_empresas_ilogocorto_empresas_ilogolargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ilogocorto',
            field=models.ImageField(blank=True, default='logo2.png', null=True, upload_to='static/factorweb/images/logo/'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ilogolargo',
            field=models.ImageField(blank=True, default='logo1.png', null=True, upload_to='static/factorweb/images/logo/'),
        ),
    ]
