# Generated by Django 4.2.5 on 2024-12-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0014_alter_empresas_ilogocorto_alter_empresas_ilogolargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ilogocorto',
            field=models.ImageField(blank=True, default='logo2.png', null=True, upload_to='factorweb/images/'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ilogolargo',
            field=models.ImageField(blank=True, default='logo1.png', null=True, upload_to='anexos/'),
        ),
    ]
