# Generated by Django 5.1.5 on 2025-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0016_alter_empresas_ilogolargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ilogocorto',
            field=models.ImageField(blank=True, default='logo2.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ilogolargo',
            field=models.ImageField(blank=True, default='logo1.png', null=True, upload_to='images/'),
        ),
    ]
