# Generated by Django 5.1.5 on 2025-04-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0017_alter_empresas_ilogocorto_alter_empresas_ilogolargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dversion', models.DateField(auto_now_add=True)),
                ('ctversion', models.CharField(default='', max_length=10)),
                ('ctdescripcion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Version_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctmejora', models.CharField(default='', max_length=20)),
                ('ctdescripcion', models.TextField(default='')),
                ('ctopcionmenu', models.CharField(default='', max_length=40)),
                ('ctenlace', models.CharField(default='', max_length=100)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_detalle', to='bases.versiones')),
            ],
        ),
    ]
