# Generated by Django 5.1.5 on 2025-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0018_versiones_version_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiones',
            name='lultimaversion',
            field=models.BooleanField(default=False),
        ),
    ]
