# Generated by Django 5.1.5 on 2025-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0019_versiones_lultimaversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version_detalle',
            name='ctmejora',
            field=models.CharField(default='', max_length=50),
        ),
    ]
