# Generated by Django 5.1.5 on 2025-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0020_alter_version_detalle_ctmejora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version_detalle',
            name='ctmejora',
            field=models.CharField(default='', max_length=20),
        ),
    ]
