# Generated by Django 5.1.5 on 2025-04-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0021_alter_version_detalle_ctmejora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version_detalle',
            name='ctenlace',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='version_detalle',
            name='ctmejora',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='version_detalle',
            name='ctopcionmenu',
            field=models.CharField(default='', max_length=60),
        ),
    ]
