# Generated by Django 5.1.5 on 2026-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0023_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='nnivel',
            field=models.IntegerField(default=0),
        ),
    ]
