# Generated by Django 5.1.5 on 2026-03-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0024_alter_actividades_nnivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='cxusuariocrea',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='cxusuarioelimina',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='cxusuariomodifica',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='dmodificacion',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='dregistro',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='leliminado',
        ),
    ]
