# Generated by Django 4.0.4 on 2023-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario_cabecera',
            name='ctconcepto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario_cabecera',
            name='dcontabilizado',
            field=models.DateField(default='2023-05-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan_cuentas',
            name='ctcuenta',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan_cuentas',
            name='nnivel',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='dcontabilizado',
            field=models.DateField(default='2023-05-20'),
            preserve_default=False,
        ),
    ]
