# Generated by Django 4.0.4 on 2023-05-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_diario_cabecera_ctconcepto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxcuentagananciaejercicio',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxcuentagananciaejercicioanterior',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxcuentaivaganado',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxcuentaperdidaejercicio',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxcuentaperdidaejercicioanterior',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxcuentaporcobrar',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxpagoconcajachica',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxprotesto',
        ),
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cxsobrepago',
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='cuentagananciaejercicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_ganancia', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='cuentagananciaejercicioanterior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_gananciaanterior', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='cuentaivaganado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_ivaganado', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='cuentaperdidaejercicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_perdida', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='cuentaperdidaejercicioanterior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_perdidaanterior', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='cuentaporcobrar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_cxc', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='pagoconcajachica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_cajachica', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='protesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_protesto', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_especiales',
            name='sobrepago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_sobrepago', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentas_especiales',
            name='cxcuentaconjunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_cuentacompartida', to='contabilidad.plan_cuentas'),
        ),
    ]
