# Generated by Django 4.0.4 on 2023-05-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_datos_participantes_cxparticipante'),
        ('contabilidad', '0006_alter_cuentas_bancos_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancos',
            name='banco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_banco', to='empresa.cuentas_bancarias'),
        ),
    ]
