# Generated by Django 4.0.4 on 2023-05-24 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0003_alter_datos_participantes_cxparticipante'),
        ('contabilidad', '0007_alter_cuentas_bancos_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_tiposfactoring',
            name='tipofactoring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_tipofactoring', to='empresa.tipos_factoring'),
        ),
        migrations.CreateModel(
            name='Cuentas_tasasfactoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.plan_cuentas')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('tasafactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_tasafactoring', to='empresa.tasas_factoring')),
                ('tipofactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_tasatipofactoring', to='empresa.tipos_factoring')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
