# Generated by Django 4.0.4 on 2023-05-27 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_asignacion_lfacturagenerada'),
        ('bases', '0002_empresas_ctcontribuyenteespecial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0008_alter_cuentas_tiposfactoring_tipofactoring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_porcobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxserie1', models.CharField(max_length=3)),
                ('cxserie2', models.CharField(max_length=3)),
                ('cxnumerofactura', models.CharField(max_length=9)),
                ('demision', models.DateField()),
                ('nvalorsinivaservicios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nvalorconivaservicios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('niva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cxestado', models.CharField(max_length=1)),
                ('ctconcepto', models.TextField()),
                ('cxasiento', models.CharField(max_length=10)),
                ('cxtipodocumento', models.CharField(max_length=2)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nsaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nporcentajeiva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ldocumentoelectronicogenerado', models.BooleanField(default=False)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='asignacion_factura', to='operaciones.asignacion')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
