# Generated by Django 4.0.4 on 2023-05-27 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_documentos_porcobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos_porcobrar',
            name='cxasiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.diario_cabecera'),
        ),
    ]
