# Generated by Django 4.0.4 on 2023-06-02 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0012_ampliaciones_plazo_cabecera_lfacturagenerada'),
        ('bases', '0003_empresas_cxusuariomodifica_empresas_dmodificacion'),
        ('empresa', '0004_puntos_emision'),
        ('contabilidad', '0010_alter_documentos_porcobrar_cxasiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxnumerofactura', models.CharField(max_length=9)),
                ('demision', models.DateField()),
                ('nvalorsinivaservicios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nvalorconivaservicios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('niva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cxestado', models.CharField(max_length=1)),
                ('ctconcepto', models.TextField()),
                ('cxtipodocumento', models.CharField(max_length=2)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nsaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nporcentajeiva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ldocumentoelectronicogenerado', models.BooleanField(default=False)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='asignacion_factura', to='operaciones.asignacion')),
                ('cxasiento', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.diario_cabecera')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('puntoemision', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.puntos_emision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Items_facturaventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.factura_venta')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.tasas_factoring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Documentos_porcobrar',
        ),
    ]
