# Generated by Django 4.0.4 on 2023-06-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_factura_venta_items_facturaventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura_venta',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='factura_venta',
            name='nporcentajeiva',
        ),
        migrations.AlterField(
            model_name='factura_venta',
            name='cxasiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.diario_cabecera'),
        ),
        migrations.AlterField(
            model_name='factura_venta',
            name='cxestado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
