# Generated by Django 4.0.4 on 2023-06-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_datos_compradores_cxclase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0004_empresas_ambientesri'),
        ('contabilidad', '0012_remove_factura_venta_asignacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura_venta',
            old_name='nvalorconivaservicios',
            new_name='nbaseiva',
        ),
        migrations.RenameField(
            model_name='factura_venta',
            old_name='nvalorsinivaservicios',
            new_name='nbasenoiva',
        ),
        migrations.AddField(
            model_name='factura_venta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='clientes.datos_generales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura_venta',
            name='nporcentajeiva',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.AddField(
            model_name='items_facturaventa',
            name='lcargaiva',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Impuestos_facturaventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cximpuesto', models.CharField(max_length=3)),
                ('cxporcentaje', models.CharField(max_length=3)),
                ('nbase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.factura_venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
