# Generated by Django 4.0.4 on 2023-06-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_rename_nvalorconivaservicios_factura_venta_nbaseiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos_facturaventa',
            name='cxporcentaje',
            field=models.CharField(max_length=5),
        ),
    ]
