# Generated by Django 4.0.4 on 2023-06-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_alter_impuestos_facturaventa_cxporcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos_facturaventa',
            name='cxporcentaje',
            field=models.CharField(max_length=15),
        ),
    ]
