# Generated by Django 4.0.4 on 2023-06-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_alter_impuestos_facturaventa_cxporcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura_venta',
            name='ctconcepto',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cxtransaccion',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='dcontabilizado',
        ),
        migrations.AddField(
            model_name='factura_venta',
            name='cxtipooperacion',
            field=models.CharField(choices=[('LA', 'Liquidación de asignación'), ('LC', 'Liquidación de cobranza'), ('AP', 'Ampliación de plazo')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='factura_venta',
            name='operacion',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='diario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.diario_cabecera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impuestos_facturaventa',
            name='cxporcentaje',
            field=models.CharField(max_length=5),
        ),
    ]
