# Generated by Django 4.0.4 on 2023-06-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_datos_compradores_cxclase'),
        ('empresa', '0006_puntos_emision_ctdescripcion_puntos_emision_lactiva'),
        ('bases', '0004_empresas_ambientesri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0016_remove_factura_venta_ctconcepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_venta',
            name='cxasiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_factura', to='contabilidad.diario_cabecera'),
        ),
        migrations.CreateModel(
            name='Comprobante_egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('demision', models.DateField()),
                ('cxestado', models.CharField(default='A', max_length=1)),
                ('cxformapago', models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('TRA', 'Transferencia')], max_length=3)),
                ('cxbeneficiario', models.CharField(blank=True, max_length=13)),
                ('ctrecibidopor', models.CharField(max_length=60)),
                ('ctcheque', models.CharField(max_length=8, null=True)),
                ('cxasiento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_egreso', to='contabilidad.diario_cabecera')),
                ('cxcuentadestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuenta_transferencia')),
                ('cxcuentapago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='empresa.cuentas_bancarias')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
