# Generated by Django 4.0.4 on 2023-06-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_alter_factura_venta_cxasiento_comprobante_egreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura_venta',
            old_name='cxasiento',
            new_name='asiento',
        ),
    ]
