# Generated by Django 4.0.4 on 2023-06-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_rename_lcargo_movimientos_maestro_litemfactura'),
        ('contabilidad', '0018_rename_cxasiento_factura_venta_asiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_tasasfactoring',
            name='tasafactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_tasafactoring', to='operaciones.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='items_facturaventa',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.movimientos_maestro'),
        ),
    ]
