# Generated by Django 4.0.4 on 2023-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_alter_cuentas_tasasfactoring_tasafactoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante_egreso',
            name='nvalor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
