# Generated by Django 4.0.4 on 2023-06-18 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_empresas_ambientesri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0015_rename_lcargo_movimientos_maestro_litemfactura'),
        ('empresa', '0007_tipos_factoring_lgenerafacturaenaceptacion'),
        ('contabilidad', '0020_comprobante_egreso_nvalor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas_diferidosprovision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cuentadiferido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuentadiferido', to='contabilidad.plan_cuentas')),
                ('cuentaprovision', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_provision', to='contabilidad.plan_cuentas')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('tasafactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuentadiferido_tasafactoring', to='operaciones.movimientos_maestro')),
                ('tipofactoring', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuentadiferido_tasatipofactoring', to='empresa.tipos_factoring')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
