# Generated by Django 4.0.4 on 2023-06-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0022_cuentas_diferidos_cuentas_provisiones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas_diferidos',
            old_name='cuentadiferido',
            new_name='cuenta',
        ),
        migrations.RenameField(
            model_name='cuentas_provisiones',
            old_name='cuentaprovision',
            new_name='cuenta',
        ),
    ]
