# Generated by Django 4.0.4 on 2023-06-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0023_rename_cuentadiferido_cuentas_diferidos_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_especiales',
            name='cuentaivadiferido',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_ivadiferido', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
    ]
