# Generated by Django 4.0.4 on 2023-06-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0024_cuentas_especiales_cuentaivadiferido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas_especiales',
            old_name='cuentaivadiferido',
            new_name='ivadiferido',
        ),
    ]
