# Generated by Django 4.0.4 on 2023-06-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_rename_lcargo_movimientos_maestro_litemfactura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0004_empresas_ambientesri'),
        ('contabilidad', '0025_rename_cuentaivadiferido_cuentas_especiales_ivadiferido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas_especiales',
            name='cuentaporcobrar',
        ),
        migrations.AddField(
            model_name='cuentas_tiposfactoring',
            name='cuentaporcobrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_cxc', to='contabilidad.plan_cuentas'),
        ),
        migrations.AlterField(
            model_name='cuentas_especiales',
            name='cuentaconjunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_cuentacompartida', to='contabilidad.plan_cuentas'),
        ),
        migrations.AlterField(
            model_name='cuentas_especiales',
            name='ivadiferido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_ivadiferido', to='contabilidad.plan_cuentas'),
        ),
        migrations.AlterField(
            model_name='cuentas_especiales',
            name='protesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_protesto', to='contabilidad.plan_cuentas'),
        ),
        migrations.AlterField(
            model_name='cuentas_especiales',
            name='sobrepago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_sobrepago', to='contabilidad.plan_cuentas'),
        ),
        migrations.CreateModel(
            name='Provisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lcontabilizado', models.BooleanField(default=False)),
                ('año', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=2)),
                ('accesorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.chequesaccesorios')),
                ('asiento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_provision', to='contabilidad.diario_cabecera')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.movimientos_maestro')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.documentos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
