# Generated by Django 4.0.4 on 2023-06-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0026_remove_cuentas_especiales_cuentaporcobrar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='cxreferencia',
            new_name='ctreferencia',
        ),
        migrations.AlterField(
            model_name='cuentas_tiposfactoring',
            name='cuentaporcobrar',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_cxc', to='contabilidad.plan_cuentas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cxtipo',
            field=models.CharField(choices=[('D', 'Debe'), ('H', 'Haber')], max_length=1),
        ),
    ]
