# Generated by Django 4.0.4 on 2023-06-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0027_rename_cxreferencia_transaccion_ctreferencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante_egreso',
            old_name='cxasiento',
            new_name='asiento',
        ),
    ]
