# Generated by Django 4.0.4 on 2023-06-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_empresas_ambientesri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0030_saldos_controlmeses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControlMeses',
            new_name='Control_meses',
        ),
        migrations.RenameField(
            model_name='saldos',
            old_name='ccuenta',
            new_name='cuenta',
        ),
        migrations.CreateModel(
            name='Cuentas_nivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcuenta', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=20)),
                ('lactivo', models.BooleanField()),
                ('lingreso', models.BooleanField()),
                ('legreso', models.BooleanField()),
                ('lordeb', models.BooleanField()),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
