# Generated by Django 4.0.4 on 2023-06-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0031_rename_controlmeses_control_meses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas_nivel1',
            old_name='lordeb',
            new_name='lorden',
        ),
    ]
