# Generated by Django 4.0.4 on 2023-07-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0032_rename_lordeb_cuentas_nivel1_lorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_nivel1',
            name='cxcuenta',
            field=models.CharField(max_length=15),
        ),
    ]
