# Generated by Django 4.0.4 on 2023-07-11 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0004_empresas_ambientesri'),
        ('contabilidad', '0034_alter_saldos_ndebe_alter_saldos_ndebe00_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldos_gyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('año', models.CharField(max_length=4)),
                ('ndebe01', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe02', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe03', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe04', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe05', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe06', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe07', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe08', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe09', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe10', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe11', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe12', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber01', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber02', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber03', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber04', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber05', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber06', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber07', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber08', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber09', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber10', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber11', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber12', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe00', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber00', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ndebe', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('nhaber', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.plan_cuentas')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
