# Generated by Django 4.0.4 on 2023-07-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_tipos_factoring_lgenerafacturaenaceptacion'),
        ('contabilidad', '0035_saldos_gyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_venta',
            name='cxtipofactoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.tipos_factoring'),
        ),
        migrations.AlterField(
            model_name='factura_venta',
            name='cxtipooperacion',
            field=models.CharField(choices=[('LA', 'Liquidación de asignación'), ('LC', 'Liquidación de cobranza'), ('AP', 'Ampliación de plazo'), ('VF', 'Vencimiento de factura')], max_length=2, null=True),
        ),
    ]
