# Generated by Django 4.0.4 on 2023-08-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0040_alter_cuentas_especiales_liquidacionennegativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_especiales',
            name='comisionchequesprotestados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_notadebitobanco', to='contabilidad.plan_cuentas'),
        ),
    ]
