# Generated by Django 4.0.4 on 2024-07-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0016_remove_tasas_factoring_cttasa_movimientos_maestro_and_more'),
        ('contabilidad', '0042_cuentas_cargosfactoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_cargosfactoring',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_cargo', to='empresa.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='cuentas_diferidos',
            name='tasafactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuentadiferido_tasafactoring', to='empresa.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='cuentas_provisiones',
            name='tasafactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuentaprovision_tasafactoring', to='empresa.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='cuentas_tasasfactoring',
            name='tasafactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuenta_tasafactoring', to='empresa.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='items_facturaventa',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='provisiones',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.movimientos_maestro'),
        ),
    ]
