# Generated by Django 4.0.4 on 2024-08-06 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0011_alter_empresas_ctnombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0044_alter_cuentas_cargosfactoring_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_venta',
            name='cxtipooperacion',
            field=models.CharField(choices=[('LA', 'Liquidación de asignación'), ('LC', 'Liquidación de cobranza'), ('AP', 'Ampliación de plazo'), ('VF', 'Vencimiento de factura'), ('CP', 'Cobro de pagaré')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Cuentas_reestructuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contabilidad.plan_cuentas')),
                ('cuentainteres', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reestructuracion_interes', to='contabilidad.plan_cuentas')),
                ('cuentaporcobrar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reestructuracion_cxc', to='contabilidad.plan_cuentas')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
