# Generated by Django 5.1.5 on 2025-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0045_alter_factura_venta_cxtipooperacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante_egreso',
            name='ctcuentadestino',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante_egreso',
            name='cxformapago',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('TRA', 'Transferencia'), ('TRN', 'Transferencia'), ('DEB', 'Debito')], max_length=3),
        ),
    ]
