# Generated by Django 5.1.5 on 2025-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0046_comprobante_egreso_ctcuentadestino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante_egreso',
            name='ctcheque',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante_egreso',
            name='ctcuentadestino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
