# Generated by Django 4.0.4 on 2022-05-22 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0013_alter_tasas_factoring_cttasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_operativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dalta', models.DateTimeField(auto_created=True)),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipoliquidacioncobranza', models.CharField(default='L', max_length=1, null=True)),
                ('nporcentajeanticipo', models.SmallIntegerField(default=80)),
                ('ntasacomision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ntasadescuentocartera', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ntasagaoa', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('cxclase', models.ForeignKey(default='A', on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.clases_cliente', to_field='cxclase')),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
