# Generated by Django 4.0.4 on 2022-05-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_alter_tasas_factoring_cttasa'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_operativos',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_operativos', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
