# Generated by Django 4.0.4 on 2023-04-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_datos_compradores_cxclase'),
        ('operaciones', '0003_remove_documentos_cxtipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_asignacion', to='clientes.datos_generales'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_documento', to='clientes.datos_generales'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cxcomprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='clientes.datos_compradores'),
        ),
    ]
