# Generated by Django 4.0.4 on 2022-05-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_asignacion_cxtipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='dultimomovimiento',
        ),
    ]
