# Generated by Django 4.0.4 on 2023-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_remove_ampliaciones_plazo_cabecera_notadedebito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampliaciones_plazo_detalle',
            name='nvalorcartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
