# Generated by Django 4.0.4 on 2022-06-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_remove_asignacion_dultimomovimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='ntotalimpuesto1',
            new_name='niva',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='ctdescripcionimpuesto1',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='ctdescripcionimpuesto2',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='ntotalimpuesto2',
        ),
    ]
