# Generated by Django 4.0.4 on 2022-06-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_datos_generales_cxcliente'),
        ('operaciones', '0006_rename_ntotalimpuesto1_asignacion_niva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_operativos',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_operativos', to='clientes.datos_generales', to_field='cxcliente'),
        ),
    ]
