# Generated by Django 4.0.4 on 2023-05-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_ampliaciones_plazo_cabecera_notadebito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliaciones_plazo_cabecera',
            name='notadebito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ampliacion_notadedebito', to='operaciones.notas_debito_cabecera'),
        ),
    ]
