# Generated by Django 4.0.4 on 2022-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_alter_datos_operativos_cxcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='cxdocumento',
        ),
        migrations.AddField(
            model_name='documentos',
            name='nreferencia',
            field=models.BigIntegerField(null=True),
        ),
    ]
