# Generated by Django 4.0.4 on 2022-06-09 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_datos_compradores_cxclase_datos_compradores_cxestado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0009_remove_documentos_cxdocumento_documentos_nreferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos_maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxmovimiento', models.CharField(max_length=4, unique=True)),
                ('ctmovimiento', models.CharField(max_length=60)),
                ('cxsigno', models.CharField(max_length=1, unique=True)),
                ('lcargadescuentocartera', models.BooleanField()),
                ('nprioridad', models.SmallIntegerField()),
                ('lcolateral', models.BooleanField()),
                ('cxmovimientopadre', models.CharField(max_length=4)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipofactoring', models.CharField(max_length=3)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxoperacion', models.CharField(max_length=10)),
                ('dmovimiento', models.DateField()),
                ('cxmes', models.CharField(max_length=2)),
                ('cxaño', models.CharField(max_length=4)),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='clientes.datos_generales', to_field='cxcliente')),
                ('cxmovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestro_movimientos', to='operaciones.movimientos_maestro', to_field='cxmovimiento')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
