# Generated by Django 4.0.4 on 2023-05-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_datos_compradores_cxclase'),
        ('operaciones', '0009_alter_ampliaciones_plazo_cabecera_notadebito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='cxcliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='clientes.datos_generales'),
            preserve_default=False,
        ),
    ]
