# Generated by Django 4.0.4 on 2022-06-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_movimientos_maestro_movimientos_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_maestro',
            name='lcartera',
            field=models.BooleanField(default=False),
        ),
    ]
