# Generated by Django 4.0.4 on 2023-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_alter_desembolsos_cxcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='lfacturagenerada',
            field=models.BooleanField(default=False),
        ),
    ]
