# Generated by Django 4.0.4 on 2022-06-09 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0026_datos_compradores_cxclase_datos_compradores_cxestado_and_more'),
        ('operaciones', '0011_movimientos_maestro_lcartera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_maestro',
            name='lcartera',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='cxasignacion',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name='Cargos_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipofactoring', models.CharField(max_length=3)),
                ('cxasignacion', models.CharField(max_length=5)),
                ('cxdocumento', models.BigIntegerField(default=0, null=True)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsaldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxcobranza', models.CharField(blank=True, max_length=8)),
                ('ctformula', models.CharField(max_length=50)),
                ('dultimageneracioncargos', models.DateField()),
                ('ctvalorbase', models.CharField(max_length=15)),
                ('ndiascalculo', models.SmallIntegerField()),
                ('ntasacalculo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cxtransaccion', models.CharField(blank=True, max_length=8)),
                ('lgeneraprocesocontable', models.BooleanField(default=False)),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cargos', to='clientes.datos_generales', to_field='cxcliente')),
                ('cxmovimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.movimientos_maestro', to_field='cxmovimiento')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
