# Generated by Django 4.0.4 on 2022-06-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_remove_movimientos_maestro_lcartera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxasignacion',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
