# Generated by Django 4.0.4 on 2023-06-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_alter_factura_venta_cxasiento_comprobante_egreso'),
        ('operaciones', '0013_remove_desembolsos_nporcentajeiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desembolsos',
            name='cxasientodiario',
        ),
        migrations.RemoveField(
            model_name='desembolsos',
            name='dcontabilizado',
        ),
        migrations.AddField(
            model_name='desembolsos',
            name='cxasiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_desembolso', to='contabilidad.diario_cabecera'),
        ),
    ]
