# Generated by Django 4.0.4 on 2022-06-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_alter_asignacion_ctbancochequegarantia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_clientes',
            name='cxaño',
        ),
        migrations.RemoveField(
            model_name='movimientos_clientes',
            name='cxmes',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='lcartacesiongenerada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
