# Generated by Django 4.0.4 on 2023-07-31 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0016_documentos_lfacturagenerada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxmovimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cargo_movimiento', to='operaciones.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxtipooperacion',
            field=models.CharField(choices=[('L', 'Liquidación'), ('C', 'Cobranza'), ('R', 'Recuperación'), ('B', 'Bancaria'), ('A', 'Ampliación de plazo'), ('F', 'Factural al vencimiento')], max_length=1, null=True),
        ),
    ]
