# Generated by Django 4.0.4 on 2022-06-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0016_alter_movimientos_maestro_cxsigno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='dultimageneraciondecargos',
            field=models.DateTimeField(null=True),
        ),
    ]
