# Generated by Django 4.0.4 on 2022-06-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_alter_documentos_dultimageneraciondecargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='cxpignorado',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cxusuarioprorroga',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dultimacobranza',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='lcastigada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='ndiasprorroga',
            field=models.SmallIntegerField(default=0),
        ),
    ]
