# Generated by Django 4.0.4 on 2023-08-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_alter_cargos_detalle_cxmovimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_maestro',
            name='lcargo',
            field=models.BooleanField(default=False),
        ),
    ]
