# Generated by Django 4.0.4 on 2022-06-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0018_alter_documentos_cxpignorado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxcobranza',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='ndiasprorroga',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
