# Generated by Django 4.0.4 on 2023-08-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0018_movimientos_maestro_lcargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desembolsos',
            name='cxplantillacontabilidad',
        ),
    ]
