# Generated by Django 4.0.4 on 2022-06-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0019_alter_cargos_detalle_cxcobranza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxtransaccion',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cargos_detalle',
            name='lgeneraprocesocontable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
