# Generated by Django 4.0.4 on 2023-09-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_alter_datos_participantes_actividad'),
        ('operaciones', '0019_remove_desembolsos_cxplantillacontabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='cxcuentapago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='empresa.cuentas_bancarias'),
        ),
    ]
