# Generated by Django 4.0.4 on 2023-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0020_alter_desembolsos_cxcuentapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='lanexosimpresos',
            field=models.BooleanField(default=False),
        ),
    ]
