# Generated by Django 4.0.4 on 2022-06-16 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_alter_tipos_factoring_ctinicialesasignacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0020_alter_cargos_detalle_cxtransaccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condiciones_operativas_cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('ctcondicion', models.CharField(max_length=40)),
                ('lactiva', models.BooleanField(default=True)),
                ('laplicaafacturaspuras', models.BooleanField(default=True)),
                ('laplicaaaccesorios', models.BooleanField(default=True)),
                ('cxtipofactoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.tipos_factoring', to_field='cxtipofactoring')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condiciones_operativas_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nplazodesde', models.SmallIntegerField()),
                ('nplazohasta', models.SmallIntegerField()),
                ('nporcentajeanticipo', models.SmallIntegerField()),
                ('ntasadescuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ntasagao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cxclasecliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clase_cliente', to='empresa.clases_cliente')),
                ('cxclasecomprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_compradores', to='empresa.clases_cliente')),
                ('cxcondicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.condiciones_operativas_cabecera')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
