# Generated by Django 4.0.4 on 2023-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0021_asignacion_lanexosimpresos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexos',
            name='ctrutaanexo',
        ),
        migrations.AddField(
            model_name='anexos',
            name='fanexo',
            field=models.FileField(blank=True, upload_to='anexos/'),
        ),
    ]
