# Generated by Django 4.0.4 on 2022-07-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0024_documentos_nvalornonegociado_chequesaccesorios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequesaccesorios',
            old_name='cxcuenta',
            new_name='ctcuenta',
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ctplaza',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
