# Generated by Django 4.0.4 on 2022-08-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('operaciones', '0025_rename_cxcuenta_chequesaccesorios_ctcuenta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequesaccesorios',
            old_name='nvalor',
            new_name='ntotal',
        ),
        migrations.RemoveField(
            model_name='chequesaccesorios',
            name='demision',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='cxcheque',
        ),
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='ctplaza',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='cxbanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cheque_operacion', to='pais.bancos'),
        ),
    ]
