# Generated by Django 4.0.4 on 2022-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0026_rename_nvalor_chequesaccesorios_ntotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequesaccesorios',
            name='nanticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ndescuentocartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ngao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='nplazo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentos',
            name='nanticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ndescuentocartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ngao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentos',
            name='nplazo',
            field=models.IntegerField(default=0),
        ),
    ]
