# Generated by Django 4.0.4 on 2022-08-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('operaciones', '0028_rename_nvalor_documentos_ntotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques',
            name='cxbanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cheque', to='pais.bancos'),
        ),
    ]
