# Generated by Django 4.0.4 on 2024-07-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0028_alter_cargos_detalle_cxmovimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='notroscargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
