# Generated by Django 4.0.4 on 2022-08-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0029_alter_cheques_cxbanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='dliquidacion',
            field=models.DateTimeField(null=True),
        ),
    ]
