# Generated by Django 4.0.4 on 2024-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0029_asignacion_notroscargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='jotroscargos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nbaseiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nbasenoiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
