# Generated by Django 4.0.4 on 2024-07-27 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0011_alter_empresas_ctnombre'),
        ('clientes', '0007_alter_personas_juridicas_cxtipoempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0030_asignacion_jotroscargos_asignacion_nbaseiva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demision', models.DateField(auto_created=True)),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxpagare', models.CharField(max_length=8)),
                ('dvencimiento', models.DateField()),
                ('ncapital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ninteres', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nsaldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cxestado', models.CharField(default='L', max_length=1)),
                ('ntasainteres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nplazo', models.IntegerField()),
                ('ncuotas', models.IntegerField()),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pagare', to='clientes.datos_generales')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pagare_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('ncuota', models.SmallIntegerField()),
                ('dfechapago', models.DateField()),
                ('nvalorcuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ninteres', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ncapital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nsaldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('pagare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.pagares')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
