# Generated by Django 4.0.4 on 2024-07-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0031_pagares_pagare_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagares',
            old_name='ncuotas',
            new_name='ncantidadcuotas',
        ),
        migrations.RemoveField(
            model_name='pagare_detalle',
            name='nvalorcuota',
        ),
    ]
