# Generated by Django 4.0.4 on 2022-09-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0032_anexos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexos',
            name='banexo',
        ),
        migrations.AddField(
            model_name='anexos',
            name='ctrutaanexo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
