# Generated by Django 4.0.4 on 2024-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0033_pagares_dultimacobranza_alter_pagares_cxestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagare_detalle',
            name='dultimacobranza',
            field=models.DateTimeField(null=True),
        ),
    ]
