# Generated by Django 4.0.4 on 2022-09-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0033_remove_anexos_banexo_anexos_ctrutaanexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Aceptada'), ('L', 'Liquidada')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='ctcheque',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='ntotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cheques',
        ),
    ]
