# Generated by Django 4.0.4 on 2024-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0034_pagare_detalle_dultimacobranza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagare_detalle',
            name='cxestado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
