# Generated by Django 4.0.4 on 2022-11-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0035_alter_chequesaccesorios_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos_detalle',
            name='cxcobranza',
        ),
        migrations.RemoveField(
            model_name='cargos_detalle',
            name='cxtransaccion',
        ),
    ]
