# Generated by Django 4.0.4 on 2024-08-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0035_pagare_detalle_cxestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagare_detalle',
            old_name='nsaldo',
            new_name='nsaldocapital',
        ),
        migrations.AddField(
            model_name='pagare_detalle',
            name='nsaldointeres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
