# Generated by Django 4.0.4 on 2024-08-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0036_rename_nsaldo_pagare_detalle_nsaldocapital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagare_detalle',
            old_name='nsaldocapital',
            new_name='nsaldo',
        ),
    ]
