# Generated by Django 4.0.4 on 2022-11-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0036_remove_cargos_detalle_cxcobranza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos_detalle',
            name='ctformula',
        ),
    ]
