# Generated by Django 4.2.5 on 2024-12-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0037_rename_nsaldocapital_pagare_detalle_nsaldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagare_detalle',
            options={'ordering': ['ncuota']},
        ),
    ]
