# Generated by Django 4.0.4 on 2022-11-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_alter_cuentas_bancarias_cxbanco'),
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0037_remove_cargos_detalle_ctformula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='dliquidacion',
        ),
        migrations.AddField(
            model_name='datos_operativos',
            name='ctbeneficiarioasignacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datos_operativos',
            name='ctbeneficiariocobranzas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datos_operativos',
            name='cxbeneficiarioasignacion',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='datos_operativos',
            name='cxbeneficiariocobranzas',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='Desembolsos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipooperacion', models.CharField(choices=[('A', 'Asignaciones'), ('C', 'Cobranzas')], max_length=1)),
                ('cxoperacion', models.BigIntegerField()),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cxformapago', models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('MOV', 'Movimiento contable'), ('TRA', 'Transferencia')], max_length=3)),
                ('cxbeneficiario', models.CharField(blank=True, max_length=13, null=True)),
                ('ctbeneficiario', models.TextField(blank=True, null=True)),
                ('lgeneradoarchivobanco', models.BooleanField(default=False)),
                ('cxplantillacontabilidad', models.CharField(blank=True, max_length=10, null=True)),
                ('lcontabilizado', models.BooleanField(default=False)),
                ('dcontabilizado', models.DateField(null=True)),
                ('cxasientodiario', models.CharField(blank=True, max_length=8, null=True)),
                ('nporcentajeiva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxcliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.datos_generales')),
                ('cxcuentadestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuentas_bancarias')),
                ('cxcuentapago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='empresa.cuentas_bancarias')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
