# Generated by Django 4.2.5 on 2025-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0038_alter_pagare_detalle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='cxautorizacion_ec',
            field=models.CharField(max_length=49, null=True),
        ),
    ]
