# Generated by Django 4.0.4 on 2022-11-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_alter_cuentas_bancarias_cxbanco'),
        ('operaciones', '0038_remove_asignacion_dliquidacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='cxcuentadestino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientes.cuenta_transferencia'),
        ),
    ]
