# Generated by Django 5.1.5 on 2025-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0039_documentos_cxautorizacion_ec'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_operativos',
            name='ntasamora',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
    ]
