# Generated by Django 4.0.4 on 2022-11-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0040_alter_desembolsos_cxcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxasignacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='operaciones.asignacion'),
        ),
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxdocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='operaciones.documentos'),
        ),
    ]
