# Generated by Django 5.1.5 on 2025-03-08 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0016_alter_empresas_ilogolargo'),
        ('clientes', '0010_alter_cupos_compradores_options_and_more'),
        ('operaciones', '0040_datos_operativos_ntasamora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision_cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('drevision', models.DateField()),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revision_cartera_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nvencidomas30', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nvencido30', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nporvencer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nprotesto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nlineaactual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ctclaseactual', models.CharField(max_length=1)),
                ('ctestadoactual', models.CharField(max_length=1)),
                ('ctcomentario', models.TextField()),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.datos_generales')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.revision_cartera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
