# Generated by Django 5.1.5 on 2025-03-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0041_revision_cartera_revision_cartera_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='nlineaactual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='nporvencer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='nprotesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='nvencido30',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='nvencidomas30',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
