# Generated by Django 4.0.4 on 2022-11-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0041_alter_cargos_detalle_cxasignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxasignacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='operaciones.asignacion'),
        ),
    ]
