# Generated by Django 5.1.5 on 2025-03-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0042_alter_revision_cartera_detalle_nlineaactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='ctclaseactual',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='ctestadoactual',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
