# Generated by Django 4.0.4 on 2022-11-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0023_liquidacion_cabecera_ldesembolsada'),
        ('operaciones', '0043_notas_debito_cabecera_notas_debito_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas_debito_cabecera',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranzas.cheques'),
        ),
    ]
