# Generated by Django 5.1.5 on 2025-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0044_cheques_quitados_historico_cortes_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexos',
            name='lcesionfacturas',
            field=models.BooleanField(default=False),
        ),
    ]
