# Generated by Django 4.0.4 on 2022-11-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0045_motivos_protesto_maestro_cheques_protestados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheques_protestados',
        ),
    ]
