# Generated by Django 5.1.5 on 2025-06-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0045_anexos_lcesionfacturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision_cartera',
            name='cxtipoparticipante',
            field=models.CharField(choices=[('C', 'Cliente'), ('D', 'Deudor')], default='C', max_length=1),
        ),
    ]
