# Generated by Django 4.0.4 on 2022-11-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0044_remove_datos_generales_ctbeneficiarioliquidacionasignacion_and_more'),
        ('operaciones', '0046_delete_cheques_protestados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxcliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='clientes.datos_generales', to_field='cxcliente'),
            preserve_default=False,
        ),
    ]
