# Generated by Django 5.1.5 on 2025-06-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0046_revision_cartera_cxtipoparticipante'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision_cartera_detalle',
            name='nvencido60',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='revision_cartera_detalle',
            name='nvencido90',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='revision_cartera_detalle',
            name='nvencidomas90',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='revision_cartera_detalle',
            name='ctclaseactual',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
