# Generated by Django 4.0.4 on 2022-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0047_alter_notas_debito_cabecera_cxcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxtipooperacion',
            field=models.CharField(choices=[('L', 'Liquidación'), ('C', 'Cobranza'), ('P', 'Protesto'), ('R', 'Recuperación'), ('A', 'Ampliación de plazo')], max_length=1),
        ),
    ]
