# Generated by Django 5.1.5 on 2025-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0047_revision_cartera_detalle_nvencido60_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision_cartera_detalle',
            old_name='nvencidomas30',
            new_name='nvencidomas60',
        ),
    ]
