# Generated by Django 5.1.5 on 2025-08-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0048_rename_nvencidomas30_revision_cartera_detalle_nvencidomas60'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequesaccesorios',
            name='lfacturagenerada',
            field=models.BooleanField(default=False),
        ),
    ]
