# Generated by Django 4.0.4 on 2023-01-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0048_alter_notas_debito_cabecera_cxtipooperacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas_debito_cabecera',
            name='cheque',
        ),
    ]
