# Generated by Django 4.0.4 on 2023-01-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0049_remove_notas_debito_cabecera_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxtipooperacion',
            field=models.CharField(choices=[('L', 'Liquidación'), ('C', 'Cobranza'), ('R', 'Recuperación'), ('A', 'Ampliación de plazo')], max_length=1),
        ),
    ]
