# Generated by Django 5.1.5 on 2025-09-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0049_chequesaccesorios_lfacturagenerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision_cartera_detalle',
            name='jdetalle',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='cxestado',
            field=models.CharField(choices=[('L', 'Liquidada'), ('P', 'Pagada'), ('E', 'Eliminada')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='notas_debito_detalle',
            name='cargo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='cargo_detalle_nd', to='operaciones.cargos_detalle'),
        ),
    ]
