# Generated by Django 5.1.5 on 2025-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0050_revision_cartera_detalle_jdetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Activa'), ('C', 'Cobrada'), ('E', 'Eliminada')], default='A', max_length=1),
        ),
    ]
