# Generated by Django 4.0.4 on 2023-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0050_alter_notas_debito_cabecera_cxtipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos_detalle',
            name='cxtipofactoring',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxtipooperacion',
            field=models.CharField(choices=[('L', 'Liquidación'), ('C', 'Cobranza'), ('R', 'Recuperación'), ('A', 'Ampliación de plazo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='operacion',
            field=models.BigIntegerField(null=True),
        ),
    ]
