# Generated by Django 5.1.5 on 2025-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0051_alter_notas_debito_cabecera_cxestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortes_historico',
            name='nvalorfacturas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cortes_historico',
            name='nvalorpagares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cortes_historico',
            name='nvalorprotestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
