# Generated by Django 4.0.4 on 2023-01-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('operaciones', '0051_alter_cargos_detalle_cxtipofactoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.tipos_factoring', to_field='cxtipofactoring'),
        ),
    ]
