# Generated by Django 4.0.4 on 2023-01-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0052_alter_notas_debito_cabecera_cxtipofactoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxtipooperacion',
            field=models.CharField(choices=[('L', 'Liquidación'), ('C', 'Cobranza'), ('R', 'Recuperación'), ('B', 'Bancaria'), ('A', 'Ampliación de plazo')], max_length=1, null=True),
        ),
    ]
