# Generated by Django 5.1.5 on 2026-04-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0052_cortes_historico_nvalorfacturas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_operativos',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Activo'), ('B', 'Baja'), ('I', 'Inactivo'), ('P', 'Pre legal'), ('L', 'Legal'), ('X', 'Bloqueado'), ('C', 'Cartera castigada')], default='A', max_length=1),
        ),
    ]
