# Generated by Django 4.0.4 on 2023-01-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0053_alter_notas_debito_cabecera_cxtipooperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos_clientes',
            name='cxtipofactoring',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
