# Generated by Django 5.1.5 on 2026-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0053_alter_datos_operativos_cxestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='cxtipooperacion',
            field=models.CharField(choices=[('A', 'Asignación'), ('C', 'Cobranza')], max_length=1),
        ),
    ]
