# Generated by Django 4.0.4 on 2023-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0054_alter_movimientos_clientes_cxtipofactoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxasignacion',
            field=models.CharField(max_length=8),
        ),
    ]
