# Generated by Django 4.0.4 on 2023-02-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0055_alter_asignacion_cxasignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_maestro',
            name='lcargadescuentocartera',
        ),
    ]
