# Generated by Django 4.0.4 on 2023-02-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0056_remove_movimientos_maestro_lcargadescuentocartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_operativos',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Activo'), ('B', 'Baja'), ('I', 'Inactivo'), ('P', 'Pre legal'), ('L', 'Legal'), ('X', 'Bloqueado')], default='A', max_length=1),
        ),
    ]
