# Generated by Django 4.0.4 on 2023-02-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0057_datos_operativos_cxestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxestado',
            field=models.CharField(choices=[('L', 'Liquidada'), ('P', 'Pagada')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='cxtipo',
            field=models.CharField(choices=[('A', 'Con accesorios'), ('F', 'Facturas puras')], max_length=1),
        ),
    ]
