# Generated by Django 4.0.4 on 2023-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0058_alter_asignacion_cxestado_alter_asignacion_cxtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_operativos',
            name='dultimanegociacion',
            field=models.DateField(null=True),
        ),
    ]
