# Generated by Django 4.0.4 on 2023-02-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0059_datos_operativos_dultimanegociacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='demision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dvencimiento',
            field=models.DateField(),
        ),
    ]
