# Generated by Django 4.0.4 on 2023-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0060_alter_documentos_demision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='dvencimiento',
            field=models.DateField(),
        ),
    ]
