# Generated by Django 4.0.4 on 2023-03-02 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0049_alter_datos_compradores_cxestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0061_alter_chequesaccesorios_dvencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequesaccesorios',
            name='cxpropietariocuenta',
            field=models.CharField(choices=[('C', 'Cliente'), ('D', 'Deudor')], default='D', max_length=1),
        ),
        migrations.CreateModel(
            name='Cheques_canjeados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('ctmotivocanje', models.CharField(max_length=60)),
                ('accesorionuevo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_nuevo', to='operaciones.chequesaccesorios')),
                ('accesoriooriginal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cheque_original', to='operaciones.chequesaccesorios')),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_canje', to='clientes.datos_generales', to_field='cxcliente')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
