# Generated by Django 4.0.4 on 2023-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0062_chequesaccesorios_cxpropietariocuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ncanjeadopor',
            field=models.BigIntegerField(null=True),
        ),
    ]
