# Generated by Django 4.0.4 on 2023-03-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0064_chequesaccesorios_laccesorioquitado_cheques_quitados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='chequequitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accesorio_quitado', to='operaciones.cheques_quitados'),
        ),
    ]
