# Generated by Django 4.0.4 on 2023-03-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0065_alter_chequesaccesorios_chequequitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='laccesorioquitado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
