# Generated by Django 4.0.4 on 2023-03-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0066_alter_chequesaccesorios_laccesorioquitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='ddesembolso',
            field=models.DateField(auto_created=True),
        ),
    ]
