# Generated by Django 4.0.4 on 2023-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0068_ampliaciones_plazo_cabecera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequesaccesorios',
            name='dultimageneraciondecargos',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ndescuentocarteraap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ngaoaap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='nplazoap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ntasacomisionap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ntasadescuentoap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ndescuentocarteraap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ngaoaap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='nplazoap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ntasacomisionap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ntasadescuentoap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dultimageneraciondecargos',
            field=models.DateField(null=True),
        ),
    ]
