# Generated by Django 4.0.4 on 2023-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0069_chequesaccesorios_dultimageneraciondecargos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='nplazoap',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nplazoap',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
