# Generated by Django 4.0.4 on 2023-03-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0049_alter_datos_compradores_cxestado'),
        ('operaciones', '0070_alter_chequesaccesorios_nplazoap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampliaciones_plazo_cabecera',
            name='cxampliacion',
        ),
        migrations.RemoveField(
            model_name='ampliaciones_plazo_detalle',
            name='documento',
        ),
        migrations.AddField(
            model_name='ampliaciones_plazo_cabecera',
            name='cxcliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='clientes.datos_generales', to_field='cxcliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ampliaciones_plazo_cabecera',
            name='ncomision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ampliaciones_plazo_cabecera',
            name='ndescuentodecartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ampliaciones_plazo_cabecera',
            name='niva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ampliaciones_plazo_detalle',
            name='cxtipoasignacion',
            field=models.CharField(choices=[('F', 'Factura pura'), ('A', 'Accesorio')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ampliaciones_plazo_detalle',
            name='documentoaccesorio',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ampliaciones_plazo_cabecera',
            name='notadedebito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operaciones.notas_debito_cabecera', to_field='cxnotadebito'),
        ),
    ]
