# Generated by Django 4.0.4 on 2023-04-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0073_remove_movimientos_maestro_nprioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos',
            name='ctnombre',
            field=models.TextField(),
        ),
    ]
