# Generated by Django 4.0.4 on 2023-04-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_alter_funcionarios_cxfuncionario_and_more'),
        ('operaciones', '0074_alter_anexos_ctnombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipofactoring_asignacion', to='empresa.tipos_factoring'),
        ),
        migrations.AlterField(
            model_name='condiciones_operativas_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.tipos_factoring'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_factoring', to='empresa.tipos_factoring'),
        ),
        migrations.AlterField(
            model_name='notas_debito_cabecera',
            name='cxtipofactoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.tipos_factoring'),
        ),
    ]
