# Generated by Django 4.0.4 on 2023-04-15 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('pais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipo', models.CharField(choices=[('A', 'Con accesorios'), ('F', 'Facturas puras')], max_length=1)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ncantidaddocumentos', models.SmallIntegerField(default=0)),
                ('cxestado', models.CharField(choices=[('A', 'Aceptada'), ('R', 'Rechazada'), ('P', 'Pendiente')], default='P', max_length=1)),
                ('datencion', models.DateTimeField(null=True)),
                ('cxusuarioatencion', models.IntegerField(null=True)),
                ('asignacion', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcomprador', models.CharField(max_length=13)),
                ('ctcomprador', models.CharField(max_length=60)),
                ('ctserie1', models.CharField(max_length=3, null=True)),
                ('ctserie2', models.CharField(max_length=3, null=True)),
                ('ctdocumento', models.CharField(max_length=9)),
                ('demision', models.DateField()),
                ('dvencimiento', models.DateField()),
                ('nvalorantesiva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('niva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nretencioniva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nretencionrenta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ntotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nvalornonegociado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nporcentajeanticipo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ntasacomision', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ntasadescuento', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('nanticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ngao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndescuentocartera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nplazo', models.IntegerField(default=0)),
                ('cxasignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.asignacion')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcliente', models.CharField(max_length=13, unique=True)),
                ('ctnombre', models.CharField(max_length=100)),
                ('cxzona', models.CharField(max_length=5, null=True)),
                ('cxlocalidad', models.CharField(max_length=4, null=True)),
                ('ctdireccion', models.TextField(null=True)),
                ('ctemail', models.EmailField(max_length=254, null=True)),
                ('ctemail2', models.EmailField(blank=True, max_length=254, null=True)),
                ('cttelefono1', models.CharField(blank=True, max_length=30, null=True)),
                ('cttelefono2', models.CharField(blank=True, max_length=30, null=True)),
                ('ctcelular', models.CharField(blank=True, max_length=30, null=True)),
                ('ctgirocomercial', models.TextField(null=True)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChequesAccesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxpropietariocuenta', models.CharField(choices=[('C', 'Cliente'), ('D', 'Deudor')], default='D', max_length=1)),
                ('ctcuenta', models.CharField(max_length=15)),
                ('ctcheque', models.CharField(max_length=13)),
                ('ctgirador', models.CharField(max_length=60)),
                ('ntotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dvencimiento', models.DateField()),
                ('nporcentajeanticipo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ntasacomision', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ntasadescuento', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('nanticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ngao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndescuentocartera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nplazo', models.IntegerField(default=0)),
                ('cxbanco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cheque_solicitud', to='pais.bancos')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.documentos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_asignacion', to='solicitudes.clientes'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.tipos_factoring'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
        ),
    ]
