# Generated by Django 4.0.4 on 2022-05-26 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('dsolicitud', models.DateTimeField(auto_now=True)),
                ('cxcliente', models.CharField(max_length=13)),
                ('cxtipofactoring', models.CharField(max_length=3)),
                ('cxtipo', models.CharField(choices=[('A', 'Con accesorios'), ('P', 'Facturas puras')], max_length=1)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ncantidaddocumentos', models.SmallIntegerField()),
                ('latendida', models.BooleanField(default=False)),
                ('datencion', models.DateTimeField(null=True)),
                ('cxusuarioatencion', models.IntegerField(null=True)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcomprador', models.CharField(max_length=13)),
                ('ctcomprador', models.CharField(max_length=60)),
                ('ctserie1', models.CharField(max_length=3)),
                ('ctserie2', models.CharField(max_length=3)),
                ('ctdocumento', models.CharField(max_length=9)),
                ('demision', models.DateTimeField()),
                ('dvencimiento', models.DateTimeField()),
                ('nvalorantesiva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('niva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nretencioniva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nretencionrenta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cxcheque', models.IntegerField(null=True)),
                ('cxasignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.asignacion')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
