# Generated by Django 4.0.4 on 2023-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cxcliente',
            field=models.CharField(max_length=13),
        ),
        migrations.AddConstraint(
            model_name='clientes',
            constraint=models.UniqueConstraint(fields=('cxcliente', 'empresa'), name='cliente_solicitud'),
        ),
    ]
