# Generated by Django 4.0.4 on 2022-05-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_clientes_alter_asignacion_cxcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='latendida',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Aceptada'), ('R', 'Rechazada'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
    ]
