# Generated by Django 4.0.4 on 2024-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_clientes_cxcliente_clientes_cliente_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='ctcomprador',
            field=models.CharField(max_length=100),
        ),
    ]
