# Generated by Django 4.0.4 on 2022-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_remove_asignacion_latendida_asignacion_cxestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='dsolicitud',
            field=models.DateTimeField(),
        ),
    ]
