# Generated by Django 4.2.5 on 2024-10-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_documentos_ctcomprador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['ctnombre']},
        ),
    ]
