# Generated by Django 4.0.4 on 2022-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_asignacion_dsolicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='dsolicitud',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='ncantidaddocumentos',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='nvalor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='ctserie1',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='ctserie2',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
