# Generated by Django 4.2.5 on 2024-12-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_clientes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='cxautorizacion_ec',
            field=models.CharField(max_length=49, null=True),
        ),
    ]
