# Generated by Django 5.1.5 on 2025-02-08 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0016_alter_empresas_ilogolargo'),
        ('clientes', '0010_alter_cupos_compradores_options_and_more'),
        ('solicitudes', '0005_documentos_cxautorizacion_ec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.datos_generales'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ctinstrucciondepago',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cxasignacion',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cxlocalidad',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ddesembolso',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='dnegociacion',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='jotroscargos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='lrequiereaceptacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nanticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nbaseiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nbasenoiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ndescuentodecartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ngao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='niva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='notroscargos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nporcentajeiva',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.CreateModel(
            name='Solicitud_aceptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsolicitud', models.DateTimeField(auto_created=True)),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxestado', models.CharField(default='P', max_length=1)),
                ('ctusuariorespuesta', models.CharField(max_length=15, null=True)),
                ('drespuesta', models.DateTimeField(null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.asignacion')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
