# Generated by Django 4.0.4 on 2022-05-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_remove_asignacion_dsolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='notal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
