# Generated by Django 4.0.4 on 2022-05-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_documentos_notal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='notal',
        ),
        migrations.AddField(
            model_name='documentos',
            name='ntotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
