# Generated by Django 5.1.5 on 2025-02-10 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('bases', '0016_alter_empresas_ilogolargo'),
        ('solicitudes', '0006_asignacion_cliente_asignacion_ctinstrucciondepago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='lrequiereaceptacion',
            new_name='lrequiereaprobacion',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Aceptada'), ('R', 'Rechazada'), ('P', 'Pendiente'), ('L', 'Liquidada')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='Niveles_aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nmontominimo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('naprobadores', models.SmallIntegerField(default=1)),
                ('nhorasrespuestamaxima', models.SmallIntegerField(default=0)),
                ('configuracionslack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='canal_slack', to='api.configuracion_slack')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud_aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxestado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('naprobaciones', models.SmallIntegerField(default=0)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_aceptacion', to='solicitudes.asignacion')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_aprobacion', to='solicitudes.niveles_aprobacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta_aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxusuariorespuesta', models.CharField(max_length=50)),
                ('cxcanal', models.CharField(max_length=50)),
                ('cxmensaje', models.CharField(max_length=50)),
                ('cxrespuesta', models.CharField(choices=[('A', 'Aprobada'), ('R', 'Rechazada')], max_length=1)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_aprobacion', to='solicitudes.solicitud_aprobacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Solicitud_aceptacion',
        ),
    ]
