# Generated by Django 5.1.5 on 2025-02-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_rename_lrequiereaceptacion_asignacion_lrequiereaprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='solicitudaprobacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_solicitud', to='solicitudes.solicitud_aprobacion'),
        ),
        migrations.AddField(
            model_name='solicitud_aprobacion',
            name='jnotificaciones',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_aprobacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_aprobacion', to='solicitudes.solicitud_aprobacion'),
        ),
        migrations.AlterField(
            model_name='solicitud_aprobacion',
            name='asignacion',
            field=models.BigIntegerField(),
        ),
    ]
