# Generated by Django 4.0.4 on 2022-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_remove_documentos_notal_documentos_ntotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='nporcentajeanticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ntasacomision',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ntasadescuento',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
    ]
