# Generated by Django 4.0.4 on 2022-06-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_documentos_nporcentajeanticipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='demision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dvencimiento',
            field=models.DateField(),
        ),
    ]
