# Generated by Django 5.1.5 on 2025-02-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cupos_compradores_options_and_more'),
        ('solicitudes', '0008_asignacion_solicitudaprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_comprador', to='clientes.datos_compradores'),
        ),
        migrations.AlterField(
            model_name='solicitud_aprobacion',
            name='cxestado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada'), ('X', 'Cancelada')], default='P', max_length=1),
        ),
    ]
