# Generated by Django 4.0.4 on 2022-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_documentos_demision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='ntasacomision',
        ),
        migrations.AddField(
            model_name='documentos',
            name='nanticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ndescuentocartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ngao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='documentos',
            name='nivacargado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
