# Generated by Django 5.1.5 on 2025-02-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_documentos_comprador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='nmayorplazonegociacion',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
