# Generated by Django 4.0.4 on 2022-06-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_remove_documentos_ntasacomision_documentos_nanticipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='ntasacomision',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
    ]
