# Generated by Django 5.1.5 on 2025-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_asignacion_nmayorplazonegociacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_aprobacion',
            name='cxrespuesta',
        ),
        migrations.AddField(
            model_name='respuesta_aprobacion',
            name='ctrespuesta',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
