# Generated by Django 5.1.5 on 2025-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_remove_respuesta_aprobacion_cxrespuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta_aprobacion',
            name='cxcanal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_aprobacion',
            name='cxmensaje',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_aprobacion',
            name='cxusuariorespuesta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
