# Generated by Django 5.1.5 on 2025-02-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_alter_respuesta_aprobacion_cxcanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dinicioactividades',
            field=models.DateField(help_text='fecha de inicio de actividades', null=True),
        ),
    ]
