# Generated by Django 5.1.5 on 2025-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_clientes_dinicioactividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles_aprobacion',
            name='lactivo',
            field=models.BooleanField(default=True),
        ),
    ]
