# Generated by Django 5.1.5 on 2025-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_niveles_aprobacion_lactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='lnotificaciongenerada',
            field=models.BooleanField(default=False, help_text='Indica si se ha generado la notificación de este documento'),
        ),
    ]
