# Generated by Django 4.0.4 on 2022-06-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_alter_asignacion_cxtipofactoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='nvalornonegociado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
