# Generated by Django 4.0.4 on 2022-07-14 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0015_documentos_nvalornonegociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequesAccesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxbanco', models.CharField(max_length=3)),
                ('ctcuenta', models.CharField(max_length=15)),
                ('ctcheque', models.CharField(max_length=13)),
                ('ctplaza', models.CharField(default='', max_length=30)),
                ('ctgirador', models.CharField(max_length=60)),
                ('nvalor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dvencimiento', models.DateTimeField()),
                ('nporcentajeanticipo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ntasacomision', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ntasadescuento', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('nanticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ngao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndescuentocartera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nplazo', models.IntegerField(default=0)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.documentos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
