# Generated by Django 5.1.5 on 2025-08-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_exceso_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Aceptada'), ('R', 'Reversada'), ('P', 'Pendiente'), ('L', 'Liquidada')], default='P', max_length=1),
        ),
    ]
