# Generated by Django 4.0.4 on 2022-07-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('solicitudes', '0016_chequesaccesorios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequesaccesorios',
            name='ctplaza',
        ),
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='cxbanco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='pais.bancos'),
        ),
    ]
