# Generated by Django 4.0.4 on 2022-07-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('solicitudes', '0017_remove_chequesaccesorios_ctplaza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='cxbanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pais.bancos'),
        ),
    ]
