# Generated by Django 5.1.5 on 2025-09-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_alter_asignacion_cxestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceso_temporal',
            name='cxrespuesta',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
    ]
