# Generated by Django 4.0.4 on 2022-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0018_alter_chequesaccesorios_cxbanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequesaccesorios',
            name='ntotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
