# Generated by Django 5.1.5 on 2026-01-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0018_alter_exceso_temporal_cxrespuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxestado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Reversada'), ('L', 'Liquidada'), ('A', 'Aceptada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cxasignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_asignacion', to='solicitudes.asignacion'),
        ),
    ]
