# Generated by Django 4.0.4 on 2022-08-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_chequesaccesorios_ntotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequesaccesorios',
            name='nvalor',
        ),
    ]
