# Generated by Django 5.1.5 on 2026-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_alter_asignacion_cxestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='cxtipoidentificacionsri',
            field=models.CharField(choices=[('04', 'R'), ('05', 'C'), ('06', 'P'), ('08', 'O')], default='05', help_text='Tipo de identificación del comprador según SRI', max_length=2, null=True),
        ),
    ]
