# Generated by Django 5.1.5 on 2026-09-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_documentos_cxtipoidentificacionsri'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='dliquidacionnotificada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='lliquidacionnotificada',
            field=models.BooleanField(default=False, help_text='Indica que ya se envio al cliente el correo de liquidacion'),
        ),
    ]
