# Generated by Django 4.0.4 on 2022-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_remove_chequesaccesorios_nvalor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='dvencimiento',
            field=models.DateField(),
        ),
    ]
