# Generated by Django 4.0.4 on 2022-08-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('solicitudes', '0021_alter_chequesaccesorios_dvencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='cxcheque',
        ),
        migrations.AlterField(
            model_name='chequesaccesorios',
            name='cxbanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cheque_solicitud', to='pais.bancos'),
        ),
    ]
