# Generated by Django 4.0.4 on 2022-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0022_remove_documentos_cxcheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='cxidasignacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nvalorantesiva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
