# Generated by Django 4.0.4 on 2022-09-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0023_asignacion_cxidasignacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='cxidasignacion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cxasignacion',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
