# Generated by Django 4.0.4 on 2023-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0024_remove_asignacion_cxidasignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxtipo',
            field=models.CharField(choices=[('A', 'Con accesorios'), ('F', 'Facturas puras')], max_length=1),
        ),
    ]
