# Generated by Django 4.0.4 on 2023-02-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0025_alter_asignacion_cxtipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='cxasignacion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='asignacion',
            field=models.BigIntegerField(null=True),
        ),
    ]
