# Generated by Django 4.0.4 on 2023-04-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_alter_funcionarios_cxfuncionario_and_more'),
        ('solicitudes', '0027_chequesaccesorios_cxpropietariocuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='cxtipofactoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.tipos_factoring'),
        ),
    ]
