# Generated by Django 4.0.4 on 2023-04-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('solicitudes', '0028_alter_asignacion_cxtipofactoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequesaccesorios',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentos',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
    ]
