# Generated by Django 4.0.4 on 2022-05-10 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentas_transferencias',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentas_transferencias',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cupos_compradores',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cupos_compradores',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_generales',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datos_generales',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linea_factoring',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linea_factoring',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linea_factoring_hist',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linea_factoring_hist',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personas_juridicas',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personas_juridicas',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personas_naturales',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personas_naturales',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socios',
            name='cxusuarioelimina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='leliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxtipocuenta',
            field=models.CharField(choices=[('A', 'Ahorro'), ('C', 'Corriente')], help_text='A-ahorro / C-corriente', max_length=1),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuentas_transferencias',
            name='cxtipocuenta',
            field=models.CharField(choices=[('A', 'Ahorro'), ('C', 'Corriente')], help_text='A-ahorro / C-corriente', max_length=1),
        ),
        migrations.AlterField(
            model_name='cuentas_transferencias',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cupos_compradores',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linea_factoring',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linea_factoring_hist',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personas_naturales',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socios',
            name='cxusuariocrea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL),
        ),
    ]
