# Generated by Django 4.0.4 on 2022-05-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('clientes', '0002_cuentas_bancarias_cxusuarioelimina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupos_compradores',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participante_cliente', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='cupos_compradores',
            name='cxcomprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participante_comprador', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='linea_factoring',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='linea_factoring_hist',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='personas_naturales',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
