# Generated by Django 4.0.4 on 2023-08-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_datos_compradores_cxclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupos_compradores',
            name='cxmodalidadcobranza',
        ),
    ]
