# Generated by Django 4.0.4 on 2023-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cupos_compradores_cxmodalidadcobranza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='ctemailfacturacionelectronica',
            field=models.EmailField(help_text='Dirección email para factracion electronica', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxorigen',
            field=models.CharField(help_text='Código de localidad / oficina asignada del cliente', max_length=5, null=True),
        ),
    ]
