# Generated by Django 4.0.4 on 2022-05-11 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('clientes', '0003_alter_cupos_compradores_cxcliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
        migrations.AlterField(
            model_name='cuentas_transferencias',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
