# Generated by Django 4.0.4 on 2022-05-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cuentas_bancarias_cxcliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_generales',
            old_name='dcontrato',
            new_name='fecha_contrato',
        ),
    ]
