# Generated by Django 4.0.4 on 2023-08-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_alter_datos_participantes_actividad'),
        ('clientes', '0004_alter_datos_generales_ctemailfacturacionelectronica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='cxlocalidad',
            field=models.ForeignKey(help_text='Cree más sucursales en la opción Localidades del menú Configuración/Empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.localidades'),
        ),
    ]
