# Generated by Django 4.0.4 on 2023-09-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0010_alter_empresas_ambientesri'),
        ('empresa', '0011_alter_datos_participantes_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0005_alter_datos_generales_cxlocalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_operativos_hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('nporcentajeanticipo', models.SmallIntegerField(default=80)),
                ('ntasacomision', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ntasadescuentocartera', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ntasagaoa', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('cxbeneficiarioasignacion', models.CharField(blank=True, max_length=13, null=True)),
                ('ctbeneficiarioasignacion', models.TextField(blank=True, null=True)),
                ('cxbeneficiariocobranzas', models.CharField(blank=True, max_length=13, null=True)),
                ('ctbeneficiariocobranzas', models.TextField(blank=True, null=True)),
                ('cxestado', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja'), ('I', 'Inactivo'), ('P', 'Pre legal'), ('L', 'Legal'), ('X', 'Bloqueado')], default='A', max_length=1)),
                ('cxclase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.clases_cliente')),
                ('cxcliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='datos_operativos_hist', to='clientes.datos_generales')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
