# Generated by Django 4.0.4 on 2022-05-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_rename_dcontrato_datos_generales_fecha_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_generales',
            old_name='fecha_contrato',
            new_name='dcontrato',
        ),
    ]
