# Generated by Django 4.0.4 on 2022-05-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_fecha_contrato_datos_generales_dcontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='cxtipocliente',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídico')], help_text='tipo de cliente: natural , juridico, etc', max_length=1),
        ),
    ]
