# Generated by Django 4.0.4 on 2024-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_personas_juridicas_cxtipoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_factoring',
            name='nreestructuracion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='valor de reestructuracion', max_digits=10),
        ),
    ]
