# Generated by Django 4.0.4 on 2022-05-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_datos_generales_cxtipocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_generales',
            name='cxsectoreconomico',
        ),
    ]
