# Generated by Django 4.0.4 on 2022-05-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_datos_generales_cxsectoreconomico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='ctbeneficiariodevolucion',
            field=models.CharField(help_text='beneficiario de devolucion por valores no negociados', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxactividad',
            field=models.CharField(help_text='actividad comercial segun codigo ciiu', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxfuncionario',
            field=models.CharField(help_text='funcionario asignado', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxfuncionario2',
            field=models.CharField(help_text='funcionario que comparte la comision por venta', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='cxorigen',
            field=models.CharField(help_text='codigo de localidad / oficina asignada del cliente', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='dlegal',
            field=models.DateTimeField(help_text='fecha que cae en estado de legal en proceso de envio a legal del sistema', null=True),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='dprelegal',
            field=models.DateTimeField(help_text='fecha que cae en estado de pre legal', null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='ctnombrecorto',
            field=models.TextField(blank=True, help_text='nombre de fantasia'),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxestadocivilrepresentante1',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='dvencimientocargorepresentante2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='dvencimientocargorepresentante3',
            field=models.DateField(null=True),
        ),
    ]
