# Generated by Django 4.2.5 on 2024-10-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_linea_factoring_nreestructuracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos_generales',
            options={'ordering': ['cxcliente__ctnombre']},
        ),
    ]
