# Generated by Django 4.2.5 on 2024-11-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_datos_generales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupos_compradores',
            options={'ordering': ['cxcomprador__cxcomprador__ctnombre', 'cxcliente__cxcliente__ctnombre']},
        ),
        migrations.AlterModelOptions(
            name='datos_compradores',
            options={'ordering': ['cxcomprador__ctnombre']},
        ),
    ]
