# Generated by Django 4.0.4 on 2022-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_datos_generales_ctobjetosocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_generales',
            name='ctobjetosocial',
        ),
        migrations.AddField(
            model_name='personas_juridicas',
            name='ctobjetosocial',
            field=models.TextField(default='', help_text='objeto social de la actividad del cliente'),
        ),
    ]
