# Generated by Django 5.1.5 on 2025-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_datos_generales_dprimeraoperacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxtipoempresa',
            field=models.CharField(choices=[('ANO', 'Anónima'), ('LTD', 'Responsabilidad Limitada'), ('SAS', 'Por acciones simplificadas'), ('COL', 'Nombre colectivo'), ('SIM', 'En comandita simple'), ('MIX', 'Economía mixta')], help_text='Anonima, limitada, etc.', max_length=3),
        ),
    ]
