# Generated by Django 4.0.4 on 2022-05-18 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_remove_datos_participantes_cxclase'),
        ('clientes', '0012_datos_generales_cxclase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='cxclase',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.clases_cliente', to_field='cxclase'),
        ),
        migrations.AlterField(
            model_name='datos_generales',
            name='dinicioactividades',
            field=models.DateField(help_text='fecha de inicio de actividades', null=True),
        ),
    ]
