# Generated by Django 5.1.5 on 2025-06-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_personas_juridicas_cxtipoempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea_factoring',
            name='cxexceso',
        ),
    ]
