# Generated by Django 4.0.4 on 2022-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clientes', '0014_personas_naturales_dnacimiento')]

    dependencies = [
        ('clientes', '0013_alter_datos_generales_cxclase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas_naturales',
            name='dnacimiento',
            field=models.DateField(default='20000101'),
        ),
    ]
