# Generated by Django 4.0.4 on 2022-05-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_personas_naturales_dnacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_naturales',
            name='dnacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
