# Generated by Django 5.1.5 on 2025-06-09 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_linea_factoring_exceso'),
        ('solicitudes', '0016_exceso_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_factoring',
            name='exceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exceso_linea_factoring', to='solicitudes.exceso_temporal'),
        ),
    ]
