# Generated by Django 5.1.5 on 2025-06-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_linea_factoring_exceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea_factoring',
            name='exceso',
        ),
    ]
