# Generated by Django 5.1.5 on 2025-12-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_remove_linea_factoring_exceso'),
        ('empresa', '0019_tipos_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas_juridicas',
            name='tipoempresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='empresa.tipos_empresas'),
        ),
    ]
