# Generated by Django 4.0.4 on 2022-05-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_personas_naturales_cxestadocivil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_generales',
            name='cxclase',
        ),
    ]
