# Generated by Django 4.0.4 on 2022-05-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_alter_tasas_factoring_cttasa'),
        ('clientes', '0017_remove_datos_generales_cxclase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_generales', related_query_name='dato_g', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
