# Generated by Django 5.1.5 on 2025-12-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_personas_juridicas_tipoempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas_juridicas',
            name='cxtipoempresa',
        ),
    ]
