# Generated by Django 5.1.5 on 2026-04-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_remove_personas_juridicas_cxtipoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_operativos_hist',
            name='ntasamora',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='datos_operativos_hist',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Activo'), ('B', 'Baja'), ('I', 'Inactivo'), ('P', 'Pre legal'), ('L', 'Legal'), ('X', 'Bloqueado'), ('C', 'Cartera castigada')], default='A', max_length=1),
        ),
    ]
