# Generated by Django 5.1.5 on 2026-04-14 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_datos_operativos_hist_ntasamora_and_more'),
        ('empresa', '0022_alter_datos_participantes_sectoreconomico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_generales',
            name='cxfuncionario',
        ),
        migrations.RemoveField(
            model_name='datos_generales',
            name='cxfuncionario2',
        ),
        migrations.AddField(
            model_name='datos_generales',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='funcionario_cliente', to='empresa.funcionarios'),
        ),
        migrations.AddField(
            model_name='datos_generales',
            name='funcionario2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='funcionario2_cliente', to='empresa.funcionarios'),
        ),
    ]
