# Generated by Django 5.1.5 on 2026-04-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_remove_datos_generales_cxfuncionario_and_more'),
        ('empresa', '0023_alter_funcionarios_lcomisionflat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='funcionario_cliente', to='empresa.funcionarios'),
        ),
    ]
