# Generated by Django 4.0.4 on 2022-06-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_alter_tasas_factoring_cttasa'),
        ('clientes', '0020_alter_datos_generales_cxcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_generales',
            name='cxcliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_generales', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
