# Generated by Django 4.0.4 on 2022-06-07 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_alter_datos_generales_cxcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_factoring_hist',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='linea_factoring', to='clientes.datos_generales', to_field='cxcliente'),
        ),
    ]
