# Generated by Django 4.0.4 on 2022-06-09 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_alter_tasas_factoring_cttasa'),
        ('clientes', '0025_alter_linea_factoring_cxcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_compradores',
            name='cxclase',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.clases_cliente', to_field='cxclase'),
        ),
        migrations.AddField(
            model_name='datos_compradores',
            name='cxestado',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='datos_compradores',
            name='cxcomprador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_generales_comprador', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
