# Generated by Django 4.0.4 on 2022-06-16 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_datos_compradores_cxclase_datos_compradores_cxestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupos_compradores',
            name='cxcomprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comprador_comprador', to='clientes.datos_compradores', to_field='cxcomprador'),
        ),
        migrations.AlterField(
            model_name='cupos_compradores',
            name='cxtipocupo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cupos_compradores',
            name='ncupocartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cupos_compradores',
            name='nutilizadocartera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datos_compradores',
            name='ctemailfacturacionelectronica',
            field=models.EmailField(help_text='direccion email para facturación electrónica', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datos_compradores',
            name='cxactividad',
            field=models.CharField(help_text='actividad comercial segun código ciiu', max_length=10, null=True),
        ),
    ]
