# Generated by Django 4.0.4 on 2022-06-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_alter_cupos_compradores_cxcomprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupos_compradores',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comprador_cliente', to='clientes.datos_generales', to_field='cxcliente'),
        ),
    ]
