# Generated by Django 4.0.4 on 2022-08-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('clientes', '0028_alter_cupos_compradores_cxcliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas_transferencias',
            old_name='cxcuenta',
            new_name='ctcuenta',
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='ctnombrepropietario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='cxidpropietario',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='cxtipoidpropietario',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='ldefault',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='lpropia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentas_transferencias',
            name='lpropia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxbanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cliente', to='pais.bancos'),
        ),
        migrations.AlterField(
            model_name='cuentas_transferencias',
            name='ctnombrepropietario',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cuentas_transferencias',
            name='cxbanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_transferencia_cliente', to='pais.bancos'),
        ),
        migrations.AlterField(
            model_name='cuentas_transferencias',
            name='cxidpropietario',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas_transferencias',
            name='cxtipoidpropietario',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
