# Generated by Django 4.0.4 on 2022-08-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_rename_cxcuenta_cuentas_transferencias_ctcuenta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuentas_transferencias',
        ),
    ]
