# Generated by Django 4.0.4 on 2022-08-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_delete_cuentas_transferencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='ctnombrepropietario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.datos_generales', to_field='cxcliente'),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxidpropietario',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxtipoidpropietario',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
