# Generated by Django 4.0.4 on 2022-08-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_alter_cuentas_bancarias_ctnombrepropietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_cliente', to='clientes.datos_generales', to_field='cxcliente'),
        ),
    ]
