# Generated by Django 4.0.4 on 2022-08-23 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0032_alter_cuentas_bancarias_cxcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='clientes.datos_generales', to_field='cxcliente'),
        ),
        migrations.CreateModel(
            name='Cuenta_transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxcliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_cliente', to='clientes.datos_generales', to_field='cxcliente')),
                ('cxcuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_transferencia', to='clientes.cuentas_bancarias')),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
