# Generated by Django 4.0.4 on 2022-08-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0034_remove_cuentas_bancarias_ldefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxtipoidpropietario',
            field=models.CharField(blank=True, choices=[('C', 'Cédula'), ('R', 'RUC'), ('E', 'extranjero')], max_length=1, null=True),
        ),
    ]
