# Generated by Django 4.0.4 on 2022-08-25 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_alter_tipos_factoring_ctinicialesasignacion'),
        ('clientes', '0035_alter_cuentas_bancarias_cxtipoidpropietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
