# Generated by Django 4.0.4 on 2022-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0037_alter_personas_juridicas_cxcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas_juridicas',
            name='dinicioactividades',
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='ctcargorepresentante2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='ctcargorepresentante3',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='ctrepresentante2',
            field=models.TextField(help_text='Nombre de segundo representante', null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='ctrepresentante3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cttelefonorepresentante2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cttelefonorepresentante3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxestadocivilrepresentante1',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('U', 'unión libre'), ('D', 'Divorciado')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxestadocivilrepresentante2',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('U', 'unión libre'), ('D', 'Divorciado')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxestadocivilrepresentante3',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('U', 'unión libre'), ('D', 'Divorciado')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxrepresentante2',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxrepresentante3',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='personas_juridicas',
            name='cxtipoempresa',
            field=models.CharField(choices=[('ANO', 'Anónima'), ('LTD', 'Limitada')], help_text='Anonima, limitada, etc.', max_length=3),
        ),
    ]
