# Generated by Django 4.0.4 on 2022-10-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
        ('clientes', '0040_rename_cxcliente_cuentas_bancarias_cxparticipante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxparticipante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='empresa.datos_participantes', to_field='cxparticipante'),
        ),
    ]
