# Generated by Django 4.0.4 on 2022-10-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('clientes', '0041_alter_cuentas_bancarias_cxparticipante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxbanco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='banco_cliente', to='pais.bancos'),
        ),
    ]
