# Generated by Django 4.0.4 on 2022-11-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_alter_cuentas_bancarias_cxbanco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_generales',
            name='ctbeneficiarioliquidacionasignacion',
        ),
        migrations.RemoveField(
            model_name='datos_generales',
            name='ctbeneficiarioliquidacioncobranza',
        ),
    ]
