# Generated by Django 4.0.4 on 2023-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0044_remove_datos_generales_ctbeneficiarioliquidacionasignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_naturales',
            name='ctnombreconyuge',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='personas_naturales',
            name='cxconyuge',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
