# Generated by Django 4.0.4 on 2023-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0045_alter_personas_naturales_ctnombreconyuge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_compradores',
            name='cxactividad',
        ),
        migrations.RemoveField(
            model_name='datos_generales',
            name='cxactividad',
        ),
        migrations.RemoveField(
            model_name='datos_generales',
            name='dinicioactividades',
        ),
    ]
