# Generated by Django 4.0.4 on 2023-02-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0047_datos_generales_cxlocalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_generales',
            name='cxestado',
        ),
    ]
