# Generated by Django 4.0.4 on 2023-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0048_remove_datos_generales_cxestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_compradores',
            name='cxestado',
            field=models.CharField(choices=[('A', 'Activo'), ('X', 'Bloqueado')], default='A', max_length=1),
        ),
    ]
