# Generated by Django 4.0.4 on 2023-04-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('clientes', '0049_alter_datos_compradores_cxestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta_transferencia',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cupos_compradores',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_compradores',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_generales',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea_factoring',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea_factoring_hist',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas_juridicas',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas_naturales',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socios',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
    ]
