# Generated by Django 4.0.4 on 2022-05-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_participantes',
            name='ctcelular',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='cttelefono1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='cttelefono2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='cxlocalidad',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='cxzona',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
