# Generated by Django 4.0.4 on 2023-04-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_remove_documentos_cxtipodocumento'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipos_documentos',
        ),
    ]
