# Generated by Django 4.0.4 on 2023-05-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_delete_tipos_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_participantes',
            name='cxparticipante',
            field=models.CharField(max_length=13),
        ),
    ]
