# Generated by Django 4.0.4 on 2022-05-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_datos_participantes_ctdireccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_participantes',
            name='ctemail2',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
