# Generated by Django 4.0.4 on 2022-05-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_datos_participantes_ctemail2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_participantes',
            name='cxclase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.clases_cliente', to_field='cxclase'),
        ),
    ]
