# Generated by Django 4.0.4 on 2023-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_puntos_emision_nultimasecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos_emision',
            name='ctdescripcion',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntos_emision',
            name='lactiva',
            field=models.BooleanField(default=True),
        ),
    ]
