# Generated by Django 4.0.4 on 2022-05-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_datos_participantes_cxclase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_participantes',
            name='cxtipoid',
            field=models.CharField(choices=[('C', 'CEDULA'), ('R', 'RUC'), ('P', 'PASAPORTE'), ('O', 'OTRO')], max_length=1),
        ),
    ]
