# Generated by Django 4.0.4 on 2023-06-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_puntos_emision_ctdescripcion_puntos_emision_lactiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_factoring',
            name='lgenerafacturaenaceptacion',
            field=models.BooleanField(default=True),
        ),
    ]
