# Generated by Django 4.0.4 on 2022-05-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_datos_participantes_cxtipoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_participantes',
            name='ctcelular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='ctemail2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='ctnombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='cttelefono1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='cttelefono2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
