# Generated by Django 4.0.4 on 2022-05-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_alter_datos_participantes_ctcelular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_participantes',
            name='cxclase',
        ),
    ]
