# Generated by Django 4.0.4 on 2023-08-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_tipos_factoring_lgenerafacturaenaceptacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipos_factoring',
            name='cxtipofactoring',
        ),
    ]
