# Generated by Django 4.0.4 on 2022-05-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0008_remove_datos_participantes_cxclase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_factoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipofactoring', models.CharField(max_length=3, unique=True)),
                ('cttipofactoring', models.CharField(max_length=40)),
                ('ctabreviacion', models.CharField(max_length=30)),
                ('cxmoneda', models.CharField(max_length=3)),
                ('nvalorminimopordocumento', models.DecimalField(decimal_places=0, max_digits=10)),
                ('lmanejalineafactoring', models.BooleanField(default=True)),
                ('lanticipatotalnegociado', models.BooleanField(default=False)),
                ('ndiasgracia', models.IntegerField(default=5)),
                ('lpermitediasferiados', models.BooleanField(default=False)),
                ('lmanejacondicionesoperativas', models.BooleanField(default=True)),
                ('lgeneradcenaceptacion', models.BooleanField(default=True)),
                ('lgeneragaoenaceptacion', models.BooleanField(default=True)),
                ('lesnegociada', models.BooleanField(default=True)),
                ('lcobramorabc', models.BooleanField(default=False)),
                ('nporcentajeretencionenfactura', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ctinicialesliquidacioncobranza', models.CharField(max_length=3)),
                ('lacumulagaoaatasagao', models.BooleanField(default=False)),
                ('lfactoringproveedores', models.BooleanField(default=False)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos_documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtipodocumento', models.CharField(max_length=1, unique=True)),
                ('cttipodocumento', models.CharField(max_length=15)),
                ('ctabreviacion', models.CharField(blank=True, max_length=5)),
                ('lprincipal', models.BooleanField(default=True)),
                ('laccesorio', models.BooleanField(default=False)),
                ('lefectocobro', models.BooleanField(default=True)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tasas_factoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxtasa', models.CharField(max_length=4, unique=True)),
                ('cttasa', models.CharField(blank=True, max_length=30)),
                ('lflat', models.BooleanField(default=False)),
                ('ndiasperiocidad', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('ctdescripcionenreporte', models.TextField(blank=True)),
                ('limprimeenreporte', models.BooleanField(default=False)),
                ('lcargaiva', models.BooleanField(default=True)),
                ('lsobreanticipo', models.BooleanField(default=True)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxlocalidad', models.CharField(max_length=4, unique=True)),
                ('ctlocalidad', models.CharField(blank=True, max_length=80)),
                ('lactiva', models.BooleanField(default=True)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxfuncionario', models.CharField(max_length=5, unique=True)),
                ('ctfuncionario', models.CharField(max_length=100)),
                ('nporcentajecomision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lcomisionflat', models.BooleanField()),
                ('nperiocidadcomision', models.DecimalField(decimal_places=2, default=360, max_digits=5)),
                ('lcomisionsobregao', models.BooleanField(default=False)),
                ('lcomisionsobredescuentocartera', models.BooleanField(default=False)),
                ('lcomisionsobrecartera', models.BooleanField(default=False)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
