# Generated by Django 4.0.4 on 2022-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_tipos_factoring_tipos_documentos_tasas_factoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_factoring',
            name='lcargagaoa',
            field=models.BooleanField(default=True),
        ),
    ]
