# Generated by Django 4.0.4 on 2022-05-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_tipos_factoring_lcargagaoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_factoring',
            name='ctinicialesliquidacioncobranza',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='tipos_factoring',
            name='nvalorminimopordocumento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
