# Generated by Django 4.0.4 on 2023-10-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0003_actividades'),
        ('empresa', '0011_alter_datos_participantes_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxbanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pais.bancos'),
        ),
    ]
