# Generated by Django 4.0.4 on 2022-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_alter_tipos_factoring_ctinicialesliquidacioncobranza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_factoring',
            name='nporcentajeretencionenfactura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
