# Generated by Django 4.0.4 on 2022-05-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_alter_tipos_factoring_nporcentajeretencionenfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasas_factoring',
            name='cttasa',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
