# Generated by Django 4.0.4 on 2024-07-10 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0011_alter_empresas_ctnombre'),
        ('empresa', '0012_alter_cuentas_bancarias_cxbanco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otros_cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('ctcargo', models.CharField(max_length=60)),
                ('ctabreviacion', models.CharField(max_length=30)),
                ('lcargaiva', models.BooleanField(default=True)),
                ('lcargaenliquidacionasignacion', models.BooleanField(default=False)),
                ('lcargaenliquidacioncobranza', models.BooleanField(default=False)),
                ('nvalor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lactivo', models.BooleanField(default=True)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
