# Generated by Django 4.0.4 on 2022-06-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_alter_tasas_factoring_cttasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_factoring',
            name='ctinicialesasignacion',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
