# Generated by Django 4.0.4 on 2022-06-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_tipos_factoring_ctinicialesasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_factoring',
            name='ctinicialesasignacion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
