# Generated by Django 4.0.4 on 2024-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_tipos_factoring_laplicaotroscargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otros_cargos',
            name='ctcargo',
        ),
        migrations.AddField(
            model_name='otros_cargos',
            name='movimiento',
            field=models.BigIntegerField(null=True),
        ),
    ]
