# Generated by Django 4.0.4 on 2024-07-15 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0011_alter_empresas_ctnombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0015_remove_otros_cargos_ctcargo_otros_cargos_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasas_factoring',
            name='cttasa',
        ),
        migrations.CreateModel(
            name='Movimientos_maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('cxmovimiento', models.CharField(max_length=4)),
                ('ctmovimiento', models.CharField(max_length=60)),
                ('cxsigno', models.CharField(choices=[('+', 'Suma'), ('-', 'Resta')], max_length=1)),
                ('litemfactura', models.BooleanField(default=False)),
                ('lcolateral', models.BooleanField()),
                ('cxmovimientopadre', models.CharField(max_length=4)),
                ('lcargo', models.BooleanField(default=False)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tasas_factoring',
            name='movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.movimientos_maestro'),
        ),
        migrations.AlterField(
            model_name='otros_cargos',
            name='movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.movimientos_maestro'),
        ),
    ]
