# Generated by Django 4.0.4 on 2022-09-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('empresa', '0015_alter_tipos_factoring_ctinicialesasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxbanco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='pais.bancos'),
        ),
    ]
