# Generated by Django 4.0.4 on 2022-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0016_alter_cuentas_bancarias_cxbanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='ctrutaarchivobanco',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='cxciabco',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas_bancarias',
            name='ncheque',
            field=models.IntegerField(null=True),
        ),
    ]
