# Generated by Django 4.0.4 on 2024-07-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0016_remove_tasas_factoring_cttasa_movimientos_maestro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otros_cargos',
            name='movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='otroscargo_movimiento', to='empresa.movimientos_maestro'),
        ),
    ]
