# Generated by Django 4.0.4 on 2023-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_cuentas_bancarias_ctrutaarchivobanco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_participantes',
            name='cxactividad',
            field=models.CharField(help_text='actividad comercial segun código ciiu', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datos_participantes',
            name='dinicioactividades',
            field=models.DateField(help_text='fecha de inicio de actividades', null=True),
        ),
    ]
