# Generated by Django 5.1.5 on 2025-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_otros_cargos_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_factoring',
            name='lacumulamoraatasadc',
            field=models.BooleanField(default=False),
        ),
    ]
