# Generated by Django 4.0.4 on 2023-02-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0018_datos_participantes_cxactividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_participantes',
            name='cxlocalidad',
        ),
        migrations.RemoveField(
            model_name='localidades',
            name='cxlocalidad',
        ),
    ]
