# Generated by Django 5.1.5 on 2026-03-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0023_actividades'),
        ('empresa', '0019_tipos_empresas'),
        ('pais', '0004_remove_actividades_cxusuariocrea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_participantes',
            name='canton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pais.cantones'),
        ),
        migrations.AddField(
            model_name='datos_participantes',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pais.provincias'),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bases.actividades'),
        ),
    ]
