# Generated by Django 4.0.4 on 2023-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0020_tasas_factoring_ctinicialesentablas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_factoring',
            name='lcargadcenampliacionplazo',
            field=models.BooleanField(default=False),
        ),
    ]
