# Generated by Django 5.1.5 on 2026-03-23 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0024_alter_actividades_nnivel'),
        ('empresa', '0020_datos_participantes_canton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_participantes',
            name='sectoreconomico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='participante_seCtor_economico', to='bases.actividades'),
        ),
        migrations.AlterField(
            model_name='datos_participantes',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='participante_actividad', to='bases.actividades'),
        ),
    ]
