# Generated by Django 5.1.5 on 2026-03-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0025_remove_actividades_cxusuariocrea_and_more'),
        ('empresa', '0021_datos_participantes_sectoreconomico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_participantes',
            name='sectoreconomico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='participante_sector_economico', to='bases.actividades'),
        ),
    ]
