# Generated by Django 4.0.4 on 2023-04-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0021_tipos_factoring_lcargadcenampliacionplazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cxfuncionario',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tasas_factoring',
            name='cxtasa',
            field=models.CharField(max_length=4),
        ),
    ]
