# Generated by Django 5.1.5 on 2026-04-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_alter_datos_participantes_sectoreconomico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='lcomisionflat',
            field=models.BooleanField(default=False),
        ),
    ]
