# Generated by Django 4.0.4 on 2023-04-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('empresa', '0022_alter_funcionarios_cxfuncionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases_cliente',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion_correos',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contador',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas_bancarias',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_participantes',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidades',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasas_factoring',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipos_documentos',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipos_factoring',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas'),
            preserve_default=False,
        ),
    ]
