# Generated by Django 5.1.5 on 2026-09-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0023_alter_funcionarios_lcomisionflat'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_correos',
            name='ctasuntocorreo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='configuracion_correos',
            name='ctlogincorreo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='configuracion_correos',
            name='ctnombreremitente',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='configuracion_correos',
            name='ctpasswordcorreo',
            field=models.TextField(default=''),
        ),
    ]
