# Generated by Django 5.1.5 on 2026-09-17 12:30

import bases.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_configuracion_correos_ctasuntocorreo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion_correos',
            name='ctpasswordcorreo',
            field=bases.fields.EncryptedTextField(default=''),
        ),
    ]
