# Generated by Django 5.1.5 on 2026-09-18 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0025_remove_actividades_cxusuariocrea_and_more'),
        ('empresa', '0026_cifrar_passwords_correo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claves_webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dregistro', models.DateTimeField(auto_now_add=True)),
                ('dmodificacion', models.DateTimeField(auto_now=True)),
                ('cxusuariomodifica', models.IntegerField(blank=True, null=True)),
                ('leliminado', models.BooleanField(default=False)),
                ('cxusuarioelimina', models.IntegerField(blank=True, null=True)),
                ('ctnombre', models.CharField(max_length=80)),
                ('ctdescripcion', models.TextField(blank=True, default='')),
                ('ctprefijo', models.CharField(blank=True, editable=False, max_length=12)),
                ('ctclavehash', models.CharField(blank=True, editable=False, max_length=128)),
                ('lactiva', models.BooleanField(default=True)),
                ('dexpiracion', models.DateField(blank=True, null=True)),
                ('dultimouso', models.DateTimeField(blank=True, null=True)),
                ('cxusuariocrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_usuariocrea', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='bases.empresas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
